/-
Copyright (c) 2026 Jeroen Zuiddam. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jeroen Zuiddam
-/
import AsymptoticTensorRankSemicontinuity.Prerequisites.Computability.AlgebraicClosure.GreedyProper

/-!
# `U` is a maximal ideal containing `Γ₁`

From global properness we promote Rabin's accepted set `Uset` to an ideal
`U` (the master lemma `accepted_of_mem_span`: a polynomial in `span(U ∪ Γ₁)` is
accepted, because its own stage test set generates a subideal of `span(U ∪ Γ₁)`),
show `Γ₁ ⊆ U` and `U ≠ ⊤`, and finally that `U` is maximal (Rabin `rabin.tex`:400).
-/

universe u

namespace Semicontinuity
namespace GreedyIdeal

variable {F : Type u} [Field F] [Primcodable F] [ComputableField F]

/-! ## The master lemma -/

/-- A polynomial lying in `span(U ∪ Γ₁)` is accepted: otherwise its stage test
set—whose generators all lie in `span(U ∪ Γ₁)`—would witness `1 ∈ span(U ∪ Γ₁)`,
contradicting global properness. -/
theorem accepted_of_mem_span {r : MvPolynomial ℕ F}
    (hr : r ∈ Ideal.span (Uset (F := F) ∪ Gamma1Set (F := F))) : accepted (F := F) r := by
  rw [show accepted (F := F) r ↔ acceptU (F := F) (Encodable.encode r) = true from Iff.rfl,
    acceptU_iff]
  refine ⟨canonicalCode_encode r, ?_⟩
  rw [hasCommonZero_iff_one_not_mem_span]
  intro h1
  refine one_not_mem_span_Uset_gamma1 (F := F) ?_
  -- every generator of the stage test lies in `span(U ∪ Γ₁)`
  have hsub : {g | g ∈ stageTest (F := F) (Encodable.encode r)} ⊆
      (Ideal.span (Uset (F := F) ∪ Gamma1Set (F := F)) : Set (MvPolynomial ℕ F)) := by
    intro g hg
    simp only [Set.mem_setOf_eq] at hg
    rw [stageTest, List.mem_append] at hg
    rcases hg with hgh | hgG
    · rw [headList, List.mem_append] at hgh
      rcases hgh with hga | hgr
      · -- accepted-before ⊆ U
        exact Ideal.subset_span (Or.inl (mem_acceptedList_imp_accepted (F := F) hga))
      · -- the single `r` itself
        rw [List.mem_singleton] at hgr
        rw [hgr, rCode_encode]
        exact hr
    · -- Γ₁ prefix ⊆ Γ₁
      exact Ideal.subset_span (Or.inr ⟨_, hgG⟩)
  exact (Ideal.span_le.mpr hsub) h1

/-! ## `U` as an ideal -/

/-- Rabin's regressive ideal `U` (`rabin.tex`:394-400). -/
noncomputable def U : Ideal (MvPolynomial ℕ F) where
  carrier := Uset (F := F)
  zero_mem' := accepted_of_mem_span (F := F) (Submodule.zero_mem _)
  add_mem' := fun ha hb =>
    accepted_of_mem_span (F := F) (Submodule.add_mem _
      (Ideal.subset_span (Or.inl ha)) (Ideal.subset_span (Or.inl hb)))
  smul_mem' := fun c _ hx =>
    accepted_of_mem_span (F := F) (Submodule.smul_mem _ c (Ideal.subset_span (Or.inl hx)))

@[simp] theorem mem_U_iff {r : MvPolynomial ℕ F} :
    r ∈ U (F := F) ↔ accepted (F := F) r := Iff.rfl

/-- `Γ₁ ⊆ U`: every Vieta equation is accepted. -/
theorem gamma1Flat_subset_U (K : ℕ) : ∀ g ∈ gamma1Flat F K, g ∈ U (F := F) := by
  intro g hg
  rw [mem_U_iff]
  exact accepted_of_mem_span (F := F) (Ideal.subset_span (Or.inr ⟨K, hg⟩))

theorem gamma1Set_subset_U : Gamma1Set (F := F) ⊆ (U (F := F) : Set (MvPolynomial ℕ F)) := by
  rintro g ⟨K, hg⟩
  exact gamma1Flat_subset_U (F := F) K g hg

/-- `U` is a proper ideal. -/
theorem U_ne_top : U (F := F) ≠ ⊤ := by
  rw [Ne, Ideal.eq_top_iff_one, mem_U_iff]
  exact one_not_accepted (F := F)

/-! ## Maximality -/

/-- **`U` is maximal** (Rabin `rabin.tex`:400).  If `x ∉ U`, then `x`'s stage test
fails properness, so `1` lies in the ideal generated by `acceptedList ∪ {x} ∪ Γ₁`,
all of which is contained in any ideal `J ⊇ U` with `x ∈ J`. -/
theorem U_isMaximal : (U (F := F)).IsMaximal := by
  rw [Ideal.isMaximal_iff]
  refine ⟨by rw [mem_U_iff]; exact one_not_accepted (F := F), ?_⟩
  intro J x hUJ hxU hxJ
  -- `x ∉ U` ⟹ its stage test has no common zero ⟹ `1 ∈ span (stage test)`
  have hnacc : acceptU (F := F) (Encodable.encode x) ≠ true := by
    rw [mem_U_iff] at hxU; exact hxU
  have hncz : ¬ hasCommonZero (F := F) (stageTest (F := F) (Encodable.encode x)) := fun hcz =>
    hnacc ((acceptU_iff (F := F) _).mpr ⟨canonicalCode_encode x, hcz⟩)
  have h1span : (1 : MvPolynomial ℕ F) ∈
      Ideal.span {g | g ∈ stageTest (F := F) (Encodable.encode x)} := by
    by_contra h
    exact hncz ((hasCommonZero_iff_one_not_mem_span (F := F) _).mpr h)
  -- every generator of the stage test lies in `J`
  have hsub : {g | g ∈ stageTest (F := F) (Encodable.encode x)} ⊆ (J : Set (MvPolynomial ℕ F)) := by
    intro g hg
    simp only [Set.mem_setOf_eq] at hg
    rw [stageTest, List.mem_append] at hg
    rcases hg with hgh | hgG
    · rw [headList, List.mem_append] at hgh
      rcases hgh with hga | hgr
      · exact hUJ (mem_U_iff.mpr (mem_acceptedList_imp_accepted (F := F) hga))
      · rw [List.mem_singleton] at hgr
        rw [hgr, rCode_encode]; exact hxJ
    · exact hUJ (gamma1Flat_subset_U (F := F) _ g hgG)
  exact (Ideal.span_le.mpr hsub) h1span

/-- The quotient field structure on `R/U`. -/
noncomputable instance : (U (F := F)).IsMaximal := U_isMaximal (F := F)

end GreedyIdeal
end Semicontinuity
