/-
Copyright (c) 2026 Jeroen Zuiddam. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jeroen Zuiddam
-/
import AsymptoticTensorRankSemicontinuity.ZariskiSublevel
import AsymptoticTensorRankSemicontinuity.Prerequisites.Computability.ComputableField
import Mathlib.Algebra.MvPolynomial.Monad

/-!
# Deciding `asympRank T ≤ r` (Theorem 1.1)

**Theorem 1.1** of *Asymptotic tensor rank is characterized by polynomials*
(arXiv:2411.15789, tex:296-298): for a computable field `F` (in the sense of
Rabin) and fixed `r`, membership in the sublevel set
`{T : asympRank T ≤ r}` is decidable by an algorithm.

Following the paper's proof (tex:313-318), the algorithm is *non-uniform in
`r`*: by Zariski-closedness of the sublevel set (Corollary 2.4 applied to the
asymptotic rank functional) there exist finitely many polynomials whose common
vanishing locus is the sublevel set; these polynomials are fixed constants of
the algorithm, which merely evaluates them on the input tensor.

This file provides the steps:

* `IsZariskiClosed.exists_finset_polynomials` — a Zariski-closed set is the
  common vanishing locus of finitely many polynomials (Hilbert basis theorem
  applied to its vanishing ideal).
-/

universe u v

namespace Semicontinuity

open scoped TensorProduct

variable {F : Type u} [Field F]
variable {V : Type v} [AddCommGroup V] [Module F V] [Module.Finite F V]

/-- A Zariski-closed set is the common vanishing locus of **finitely many**
polynomials: the vanishing ideal is finitely generated (Hilbert basis theorem),
and on a closed set the generators suffice. -/
theorem IsZariskiClosed.exists_finset_polynomials {A : Set V}
    (hA : IsZariskiClosed (F := F) A) :
    ∃ s : Finset (MvPolynomial (Fin (Module.finrank F V)) F),
      ∀ T : V, T ∈ A ↔ ∀ q ∈ s,
        MvPolynomial.eval (fun i => (Module.finBasis F V).repr T i) q = 0 := by
  classical
  -- The vanishing ideal is finitely generated by Noetherianity.
  obtain ⟨s, hs⟩ : (vanishingIdeal (F := F) (V := V) A).FG :=
    IsNoetherian.noetherian _
  refine ⟨s, fun T => ⟨fun hT q hq => ?_, fun hT => ?_⟩⟩
  · -- `T ∈ A`: every element of the vanishing ideal vanishes at `T`,
    -- in particular the generators.
    have hqI : q ∈ vanishingIdeal (F := F) (V := V) A := by
      rw [← hs]; exact Ideal.subset_span hq
    exact hqI T hT
  · -- All generators vanish at `T`, hence so does every element of the span
    -- (evaluation at the coordinates of `T` is a ring homomorphism), hence
    -- `T` lies in the Zariski closure of `A`, which is `A`.
    have hI : ∀ p ∈ vanishingIdeal (F := F) (V := V) A,
        MvPolynomial.eval (fun i => (Module.finBasis F V).repr T i) p = 0 := by
      intro p hp
      rw [← hs] at hp
      induction hp using Submodule.span_induction with
      | mem q hq => exact hT q hq
      | zero => simp
      | add p₁ p₂ _ _ h₁ h₂ => simp [h₁, h₂]
      | smul c p _ hp => simp [smul_eq_mul, hp]
    have : T ∈ zariskiClosure (F := F) A :=
      (mem_zariskiClosure_iff_eval_vanishingIdeal (F := F) A T).mpr hI
    rwa [hA] at this

/-! ## The asymptotic-rank sublevel set as a polynomial vanishing locus -/

section EntryPolynomials

variable {k : ℕ} {d : Fin k → ℕ+}

/-- The sublevel set `{T : asympRank T ≤ r}` on a fixed format is Zariski-closed
(Corollary 2.4 applied to the tensor-rank admissible functional). -/
theorem isZariskiClosed_asympRank_sublevel (hk : 1 ≤ k) (r : ℝ) :
    IsZariskiClosed (F := F) {T : KTensor F d | asympRank T ≤ r} := by
  have h := sublevel_zariski_closed (F := F) (tensorRankAdmissible F hk d) r
  have hset : {T : KTensor F d | asympRank T ≤ r}
      = {T : KTensor F d | (tensorRankAdmissible F hk d).regularize T ≤ r} := by
    ext T; simp [asympRank, hk]
  rw [IsZariskiClosed, hset]
  exact h

open MvPolynomial in
/-- **Entry-polynomial form.** The sublevel set `{T : asympRank T ≤ r}` is the
common vanishing locus of finitely many polynomials in the *entries* of the
tensor: the coordinates with respect to any basis are linear forms in the
entries, so the polynomials produced by
`IsZariskiClosed.exists_finset_polynomials` can be precomposed with these
linear forms. -/
theorem exists_finset_entryPolynomials_asympRank_le (hk : 1 ≤ k) (r : ℝ) :
    ∃ s : Finset (MvPolynomial (∀ i : Fin k, Fin (d i)) F),
      ∀ T : KTensor F d, asympRank T ≤ r ↔ ∀ q ∈ s, eval T q = 0 := by
  classical
  obtain ⟨s₀, hs₀⟩ :=
    (isZariskiClosed_asympRank_sublevel (F := F) (d := d) hk r).exists_finset_polynomials
  simp only [Set.mem_setOf_eq] at hs₀
  set B := Module.finBasis F (KTensor F d) with hB
  -- the coordinate of `T` at `i` is a linear form in the entries of `T`
  set L : Fin (Module.finrank F (KTensor F d)) →
      MvPolynomial (∀ i : Fin k, Fin (d i)) F := fun i =>
    ∑ j, C (B.repr (Pi.single j 1) i) * X j with hL
  have hLeval : ∀ (T : KTensor F d) i, eval T (L i) = B.repr T i := by
    intro T i
    have hT : (T : (∀ i : Fin k, Fin (d i)) → F)
        = ∑ j, T j • Pi.single j (1 : F) := by
      conv_lhs => rw [pi_eq_sum_univ T]
      refine Finset.sum_congr rfl fun j _ => ?_
      ext j'
      simp [Pi.single_apply, eq_comm]
    calc eval T (L i) = ∑ j, B.repr (Pi.single j 1) i * T j := by
          simp [hL]
      _ = B.repr (∑ j, T j • Pi.single j (1 : F)) i := by
          simp [map_sum, Finset.sum_apply', mul_comm]
      _ = B.repr T i := by rw [← hT]
  refine ⟨s₀.image (bind₁ L), fun T => ?_⟩
  have hbind : ∀ q, eval T (bind₁ L q) = eval (fun i => B.repr T i) q := by
    intro q
    have h : eval T (bind₁ L q) = eval (fun i => eval T (L i)) q :=
      aeval_bind₁ (S := F) (T : (∀ i : Fin k, Fin (d i)) → F) L q
    rw [h, show (fun i => eval T (L i)) = fun i => B.repr T i from
      funext fun i => hLeval T i]
  rw [hs₀ T]
  constructor
  · intro h q' hq'
    obtain ⟨q, hq, rfl⟩ := Finset.mem_image.mp hq'
    rw [hbind]
    exact h q hq
  · intro h q hq
    rw [← hbind]
    exact h _ (Finset.mem_image_of_mem _ hq)

end EntryPolynomials

/-! ## Theorem 1.1: deciding `asympRank T ≤ r` over a computable field -/

section Decidability

variable [Primcodable F] [ComputableField F]
variable {k : ℕ} {d : Fin k → ℕ+}

/-- Tensors of a fixed format are coded via their entry vectors. -/
noncomputable instance instPrimcodableKTensor : Primcodable (KTensor F d) :=
  Primcodable.ofEquiv (Fin (Fintype.card (∀ i : Fin k, Fin (d i))) → F)
    (Equiv.arrowCongr (Fintype.equivFin _) (Equiv.refl F))

omit [ComputableField F] in
theorem computable_entriesEquiv :
    Computable fun T : KTensor F d =>
      (Equiv.arrowCongr (Fintype.equivFin (∀ i : Fin k, Fin (d i)))
        (Equiv.refl F)) T :=
  Computable.encode_iff.mp (Computable.encode.of_eq fun _ => rfl)

open MvPolynomial in
theorem computable_eval_entries
    (q : MvPolynomial (∀ i : Fin k, Fin (d i)) F) :
    Computable fun T : KTensor F d => eval T q := by
  classical
  have h := ComputableField.computable_mvPolynomial_eval (F := F)
    (rename (Fintype.equivFin (∀ i : Fin k, Fin (d i))) q)
  refine (h.comp computable_entriesEquiv).of_eq fun T => ?_
  rw [eval_rename]
  have harr : (((Fintype.equivFin (∀ i : Fin k, Fin (d i))).arrowCongr
      (Equiv.refl F)) T ∘ ⇑(Fintype.equivFin (∀ i : Fin k, Fin (d i)))) = T := by
    funext j
    simp
  rw [harr]

open MvPolynomial in
theorem computablePred_finset_eval_eq_zero
    (s : Finset (MvPolynomial (∀ i : Fin k, Fin (d i)) F)) :
    ComputablePred fun T : KTensor F d => ∀ q ∈ s, eval T q = 0 := by
  classical
  induction s using Finset.induction_on with
  | empty =>
      exact ⟨inferInstance, ((Computable.const true).of_eq fun T => by simp)⟩
  | insert q s hq ih =>
      obtain ⟨_, ihC⟩ := ih
      have hone : ComputablePred fun T : KTensor F d => eval T q = 0 := by
        have hz := (ComputableField.computablePred_eq_const (F := F) 0).decide
        exact Computable.computablePred ((hz.comp (computable_eval_entries q)).of_eq
          fun T => by simp)
      obtain ⟨_, honeC⟩ := hone
      refine ⟨inferInstance, ?_⟩
      refine (Computable.cond honeC ihC (Computable.const false)).of_eq fun T => ?_
      by_cases h1 : eval T q = 0 <;>
        by_cases h2 : ∀ p ∈ s, eval T p = 0 <;>
          simp [h1, h2]

open MvPolynomial in
/-- **Theorem 1.1** (arXiv:2411.15789, tex:296-298), fixed-format form: over a
computable field, for every `r`, the predicate `asympRank T ≤ r` on `k`-tensors
of a fixed format is computably decidable.

Following the paper's proof (tex:313-318), the algorithm is non-uniform in `r`:
the finitely many entry-polynomials cutting out the sublevel set
(`exists_finset_entryPolynomials_asympRank_le`) are fixed constants of the
algorithm, which evaluates them on the input tensor. -/
theorem computablePred_asympRank_le (hk : 1 ≤ k) (r : ℝ) :
    ComputablePred fun T : KTensor F d => asympRank T ≤ r := by
  classical
  obtain ⟨s, hs⟩ := exists_finset_entryPolynomials_asympRank_le (F := F) (d := d) hk r
  exact (computablePred_finset_eval_eq_zero s).of_eq fun T => (hs T).symm

end Decidability

end Semicontinuity
