/-
Copyright (c) 2026 Jeroen Zuiddam. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jeroen Zuiddam
-/
import AsymptoticTensorRankSemicontinuity.AsymptoticSubrank.LSS.OrderTransfer
import AsymptoticTensorRankSemicontinuity.AsymptoticSubrank.LSS.Connectivity
import AsymptoticTensorRankSemicontinuity.AsymptoticSubrank.LSS.NonEmpty
import AsymptoticTensorRankSemicontinuity.AsymptoticSubrank.LSS.AmbientDensity
import AsymptoticTensorRankSemicontinuity.AsymptoticSubrank.LSS.ClosureReduction
import AsymptoticTensorRankSemicontinuity.AsymptoticSubrank.LSS.ImageChar
import AsymptoticTensorRankSemicontinuity.AsymptoticSubrank.LSS.DVertexBase
import Mathlib.GroupTheory.Perm.Sign

namespace LSS

variable {n : ℕ}

/-! ## Part 1 — the group-theoretic reduction to consecutive swaps.

`Transfers G e σ τ` for arbitrary `σ τ` reduces to the consecutive-swap building block. The
reduction uses NONE of the graph/connectivity content — only that `Transfers` is reflexive,
transitive, and that the building block transfers `σ` to `σ * (adjacent transposition)`. This
is the Lean shape of "the distribution is independent of the ordering ⟸ it is unchanged by
swapping two consecutive nodes" (LSS Main Lemma proof opening, tex:120). -/

/-- **Adjacent transposition at position `i`** (`i.val + 1 < n`): the permutation swapping the
positions `i` and `i+1`. We package it so the building-block hypothesis and the Mathlib
generator `Equiv.swap i.castSucc i.succ` line up. -/
def adjSwap (i : Fin n) (hi : i.val + 1 < n) : Equiv.Perm (Fin n) :=
  Equiv.swap i ⟨i.val + 1, hi⟩

/-- **Right-multiplication transport of `Transfers`.**
Abstract bridge: suppose that for every ordering `ρ` and every adjacent-position transposition
`adjSwap i hi` (swap of positions `i, i+1`), `Transfers G e ρ (ρ * adjSwap i hi)` holds (the
consecutive-swap hypothesis). Then for every ordering `σ` and EVERY permutation `π`,
`Transfers G e σ (σ * π)`.

Proof: `π` lies in the submonoid generated by the adjacent transpositions
(`Equiv.Perm.mclosure_swap_castSucc_succ`); induct on that membership with the `∀ σ`-quantified
motive. The unit gives reflexivity (`σ * 1 = σ`); a product `a * b` chains `Transfers σ (σ*a)`
with `Transfers (σ*a) ((σ*a)*b)` via `Transfers.trans` and `mul_assoc`; the generators are
exactly the hypothesis. -/
theorem transfers_rightMul_of_consecutive {G : SimpleGraph (Fin n)} [DecidableRel G.Adj]
    {e : ℕ}
    (hcons : ∀ (ρ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n),
      Transfers G e ρ (ρ * adjSwap i hi))
    (σ : Equiv.Perm (Fin n)) (π : Equiv.Perm (Fin n)) :
    Transfers G e σ (σ * π) := by
  -- Reduce to: `π` in the closure ⟹ the `∀σ`-motive. Case on `n`.
  rcases Nat.eq_zero_or_pos n with hn0 | hnpos
  · -- `n = 0`: `Equiv.Perm (Fin 0)` is the trivial group, `π = 1`.
    subst hn0
    have : π = 1 := Subsingleton.elim _ _
    subst this
    simpa using Transfers.refl σ
  · -- `n = m + 1`: use `mclosure_swap_castSucc_succ m`.
    obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
    -- Generators in Mathlib's form.
    set gen : Set (Equiv.Perm (Fin (m + 1))) :=
      Set.range (fun i : Fin m => Equiv.swap i.castSucc i.succ) with hgen
    have htop : Submonoid.closure gen = ⊤ := Equiv.Perm.mclosure_swap_castSucc_succ m
    have hmem : π ∈ Submonoid.closure gen := by rw [htop]; exact Submonoid.mem_top π
    -- The `∀ σ`-quantified motive.
    suffices H : ∀ q ∈ Submonoid.closure gen,
        ∀ ρ : Equiv.Perm (Fin (m + 1)), Transfers G e ρ (ρ * q) by
      exact H π hmem σ
    intro q hq
    refine Submonoid.closure_induction ?_ ?_ ?_ hq
    · -- generators: `q = swap i.castSucc i.succ` is `adjSwap i.castSucc …`.
      rintro x ⟨i, rfl⟩ ρ
      simp only []
      have hi : (i.castSucc).val + 1 < m + 1 := by
        simp only [Fin.val_castSucc]; omega
      have hswap : Equiv.swap i.castSucc i.succ = adjSwap i.castSucc hi := by
        unfold adjSwap
        congr 1
      rw [hswap]
      exact hcons ρ i.castSucc hi
    · -- unit: `ρ * 1 = ρ`.
      intro ρ
      simpa using Transfers.refl ρ
    · -- product: chain `ρ * a` then `(ρ*a) * b`.
      intro a b _ _ ha hb ρ
      have h1 : Transfers G e ρ (ρ * a) := ha ρ
      have h2 : Transfers G e (ρ * a) ((ρ * a) * b) := hb (ρ * a)
      have h3 : Transfers G e ρ ((ρ * a) * b) := h1.trans h2
      rwa [mul_assoc] at h3

/-- **`prop:order`, reduced form** (gorProof `prop:order` tex:289-293). Given the
consecutive-swap building block, `GOR⁺_σ` and `GOR⁺_τ` are ATS (`Transfers G e σ τ`) for ALL
orderings `σ, τ`.

Proof: by `transfers_rightMul_of_consecutive` with `π = σ⁻¹ * τ`, `Transfers G e σ (σ * π)`;
and `σ * (σ⁻¹ * τ) = τ`. -/
theorem prop_order_of_consecutive {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (hcons : ∀ (ρ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n),
      Transfers G e ρ (ρ * adjSwap i hi))
    (σ τ : Equiv.Perm (Fin n)) :
    Transfers G e σ τ := by
  have h := transfers_rightMul_of_consecutive hcons σ (σ⁻¹ * τ)
  rwa [show σ * (σ⁻¹ * τ) = τ by group] at h

/-! ## Part 2 — the consecutive-swap building block.

`transfers_consecutive σ i hi : Transfers G e σ (σ * adjSwap i hi)`, the swap of positions
`i, i+1`. Three cases on the swapped pair `(σ i, σ (i+1))`:

* **edge**: `transfers_of_edge_swap`.
* **non-edge, `i ≥ D`**: `lem:later` (`transfers_later`).
* **non-edge, `i < D`**: `lem:base1`/`lem:ats1` (`transfers_firstD_base`).

Note the `adjSwap`-vs-`Equiv.trans` bridge: `σ * adjSwap i hi = (adjSwap i hi).trans σ`
(Mathlib perm mult is reversed composition), and `adjSwap i hi = Equiv.swap i ⟨i+1, hi⟩`, so
`transfers_of_edge_swap` applies on the nose. -/

/-- The `adjSwap` reframed as an `Equiv.trans`, matching `transfers_of_edge_swap`'s conclusion
`Transfers G e σ ((Equiv.swap i j).trans σ)`. Mathlib's perm multiplication is
`σ * t = t.trans σ`. -/
theorem mul_adjSwap_eq_trans (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n) :
    σ * adjSwap i hi = (Equiv.swap i ⟨i.val + 1, hi⟩).trans σ := by
  unfold adjSwap
  rfl

/-- **Edge sub-case of the consecutive swap** (`lem:edgeCon`, gorProof tex:363-380).
If the swapped pair `(σ i, σ (i+1))` is an EDGE of `G`, the consecutive swap transfers. Direct
wrapper of `transfers_of_edge_swap`. -/
theorem transfers_consecutive_edge {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n)
    (hedge : G.Adj (σ i) (σ ⟨i.val + 1, hi⟩))
    (hcard : ∀ v, (precNonNbrσ G σ v).card ≤ e) :
    Transfers G e σ (σ * adjSwap i hi) := by
  rw [mul_adjSwap_eq_trans]
  exact transfers_of_edge_swap G e σ ⟨i.val + 1, hi⟩ rfl hedge hcard

/-! ### The outer induction hypothesis `eq:IH` as a Lean predicate.

gorProof `eq:IH` / `(★)` (tex:295-299):
  *For all `σ`, `τ` with `σ_j = τ_j` for all `i < j ≤ n`, `GOR⁺_σ` and `GOR⁺_τ` are ATS.*

In the `Transfers` framing, "`σ_j = τ_j` for all `i < j ≤ n`" becomes "`σ' k = τ' k` for all
positions `k` with `i < k.val`" (positions are 0-indexed `Fin n`; the source's `1..n` indexing
shifts by one but the predicate is the same: *orderings agreeing on all positions strictly
beyond `i` transfer*). `eqIH G e i` is exactly the proposition `(★)` instantiated at `i`. -/
def eqIH (G : SimpleGraph (Fin n)) [DecidableRel G.Adj] (e : ℕ) (i : ℕ) : Prop :=
  ∀ (σ' τ' : Equiv.Perm (Fin n)),
    (∀ k : Fin n, i < k.val → σ' k = τ' k) → Transfers G e σ' τ'

/-- **Early-position swaps are governed by `eqIH`.** If two orderings `ρ`, `ρ'` agree on all
positions `> i` (in particular, if `ρ' = ρ * (swap of two positions both `≤ i`)`), then
`eqIH G e i` gives `Transfers G e ρ ρ'` directly. This is the Lean form of the gorProof
"exchange of *early* positions between `1` and `i`" (tex:437, steps (1),(3),(5)). -/
theorem eqIH.transfers_of_agree {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    {i : ℕ} (hIH : eqIH G e i) {ρ ρ' : Equiv.Perm (Fin n)}
    (h : ∀ k : Fin n, i < k.val → ρ k = ρ' k) :
    Transfers G e ρ ρ' :=
  hIH ρ ρ' h

/-- **A swap of two positions `a, b` with `a.val ≤ i` and `b.val ≤ i` is an early swap.**
For any `k` with `i < k.val`, `(ρ * Equiv.swap a b) k = ρ k`, because `swap a b` fixes `k`
(`k ≠ a` and `k ≠ b` since `a.val, b.val ≤ i < k.val`). Hence `eqIH G e i` transfers
`ρ` to `ρ * Equiv.swap a b`. -/
theorem eqIH.transfers_early_swap {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    {i : ℕ} (hIH : eqIH G e i) (ρ : Equiv.Perm (Fin n)) {a b : Fin n}
    (ha : a.val ≤ i) (hb : b.val ≤ i) :
    Transfers G e ρ (ρ * Equiv.swap a b) := by
  refine hIH.transfers_of_agree (fun k hk => ?_)
  have hka : k ≠ a := by intro h; rw [h] at hk; omega
  have hkb : k ≠ b := by intro h; rw [h] at hk; omega
  rw [Equiv.Perm.mul_apply, Equiv.swap_apply_of_ne_of_ne hka hkb]

/-! ### Algebraic helpers for the 5-swap conjugation.

These three proved lemmas package the purely-combinatorial content of the `lem:later`
inductive step (gorProof tex:434-454 / LSS tex:125-129):

* `five_swap_braid` — the net permutation identity: the five position-transpositions
  `s · t · s · t · s` (with `s = swap i j₁` the early swap, `t = swap i (i+1) = adjSwap i`)
  conjugate to the single swap `t`. This is the algebraic shape of "after the five exchanges the
  ordering is `ρ` with positions `i, i+1` swapped".
* `prefix_set_swap_eq` — the prefix vertex-set `{x | (ρ.symm x).val ≤ i+1}` is unchanged when `ρ`
  is right-multiplied by a transposition of two positions both `≤ i+1`. Hence all five
  intermediate orderings `σ¹,…,σ⁴` (and `ρ`, `τ`) share the SAME within-prefix induced subgraph,
  so the shorter walks fed to the inner IH live in one fixed graph.
* `withinPrefixWalkLE_of_walk` — packages a walk in `G.induce P` (with `P` propositionally equal
  to the σ-prefix set) joining the position-`i`/position-`(i+1)` vertices of `σ` into the
  `WithinPrefixWalkLE` datum the inner IH consumes. -/

/-- **The 5-swap braid identity.** For three distinct positions `i, j₁, k`,
`swap i j₁ · swap i k · swap i j₁ · swap i k · swap i j₁ = swap i k`. With `k = i+1` and
`s = swap i j₁` the early swap, `t = swap i k = adjSwap i`, this is `s·t·s·t·s = t`: the five
exchanges of `lem:later` (gorProof tex:434-454) conjugate to the single consecutive swap. -/
theorem five_swap_braid {i j1 k : Fin n} (hij : i ≠ j1) (hik : i ≠ k) (hjk : j1 ≠ k) :
    Equiv.swap i j1 * Equiv.swap i k * Equiv.swap i j1 * Equiv.swap i k * Equiv.swap i j1
      = Equiv.swap i k := by
  ext x
  simp only [Equiv.Perm.coe_mul, Function.comp_apply]
  by_cases hx : x = i
  · subst hx; simp [Equiv.swap_apply_def, hjk, Ne.symm hij, Ne.symm hik, Ne.symm hjk]
  by_cases hxj : x = j1
  · subst hxj; simp [Equiv.swap_apply_def, hjk, Ne.symm hij, Ne.symm hik, Ne.symm hjk]
  by_cases hxk : x = k
  · subst hxk; simp [Equiv.swap_apply_def, hjk, Ne.symm hij, Ne.symm hik, Ne.symm hjk]
  · simp [Equiv.swap_apply_of_ne_of_ne, hx, hxj, hxk]

/-- **The within-prefix vertex set is invariant under an early swap.** If `a.val, b.val ≤ i+1`
then `{x | ((ρ * swap a b).symm x).val ≤ i+1} = {x | (ρ.symm x).val ≤ i+1}`: right-multiplying
by a transposition of two positions inside the prefix block permutes the prefix block within
itself, leaving the SET of prefix vertices unchanged. Hence all five intermediate orderings of
`lem:later` share the same within-prefix induced subgraph. -/
theorem prefix_set_swap_eq (ρ : Equiv.Perm (Fin n)) (i : Fin n) (a b : Fin n)
    (ha : a.val ≤ i.val + 1) (hb : b.val ≤ i.val + 1) :
    {x | ((ρ * Equiv.swap a b).symm x).val ≤ i.val + 1}
      = {x | (ρ.symm x).val ≤ i.val + 1} := by
  have hsymm : ∀ x, (ρ * Equiv.swap a b).symm x = (Equiv.swap a b) (ρ.symm x) := by
    intro x
    change (Equiv.swap a b).symm (ρ.symm x) = (Equiv.swap a b) (ρ.symm x)
    rw [Equiv.symm_swap]
  ext x
  simp only [Set.mem_setOf_eq, hsymm]
  set y := ρ.symm x with hy
  by_cases hya : y = a
  · subst hya; rw [Equiv.swap_apply_left]; omega
  by_cases hyb : y = b
  · subst hyb; rw [Equiv.swap_apply_right]; omega
  · rw [Equiv.swap_apply_of_ne_of_ne hya hyb]

/-! ### `lem:later`, the 5-swap conjugation (non-edge, position `≥ D`).

gorProof `lem:later` (tex:395-456) / LSS Main Lemma 1.3 steps (1)–(5) (tex:123-130).

Setup: `G` is `(n−D)`-connected, `D ≤ i < n`, the outer IH `eq:IH` holds for `i` (passed as the
explicit hypothesis `hIH : eqIH G e i.val`, supplied by the outer induction in `prop_order`),
and `τ = σ` with positions `i, i+1` swapped (and `{σ_i, σ_{i+1}}` NOT an edge). By `lem:con`
(`Connectivity.lem_con`) there is a path `σ_i, σ_{j_1}, …, σ_{j_m}, σ_{i+1}` inside the prefix
`{x | (σ.symm x).val ≤ i+1}` with each `1 ≤ j_ℓ ≤ i-1`. The proof inducts on `k` = an upper
bound on the number of interior path vertices:

* `k = 0` (edge): `transfers_consecutive_edge`.
* `k → k+1`: the FIVE exchanges (gorProof tex:434-454 = LSS tex:125-129), each ATS-preserving
  by either the outer IH `eq:IH` (an "early-position" swap, positions `≤ i`, realized here by
  `eqIH.transfers_early_swap`) or the inner IH on `k` (a shorter-path consecutive swap) or the
  `k=0` edge base (`transfers_consecutive_edge`). Chain via `Transfers.trans`.

#### The inner induction, stated as `transfers_later_inner`.

`transfers_later_inner G e i hi hiD hIH k` says: *for every ordering `ρ` whose position-`i`/
position-`(i+1)` vertices are joined by a within-prefix walk of length `≤ k+1`, the consecutive
swap of `ρ` at position `i` transfers.* The base `k = 0` is the edge case
(`transfers_consecutive_edge`); the step `k → k+1` is the 5-exchange argument. We record the
`k = 0` base and the `k → k+1` step (the five exchanges) as separate
substatements. -/

/-- The within-prefix walk hypothesis used by the inner induction: at ordering `ρ`, the vertices
at positions `i` and `i+1` are joined by a walk in `G.induce {x | (ρ.symm x).val ≤ i+1}` of
length at most `k+1`. (Existence for the *starting* ordering is `Connectivity.lem_con`; the
inner induction reproduces it, with a strictly shorter bound, for the intermediate orderings
`σ¹,…,σ⁴`.) -/
def WithinPrefixWalkLE (G : SimpleGraph (Fin n)) (ρ : Equiv.Perm (Fin n))
    (i : Fin n) (hi : i.val + 1 < n) (k : ℕ) : Prop :=
  ∃ (hu : ρ i ∈ {x | (ρ.symm x).val ≤ i.val + 1})
    (hv : ρ ⟨i.val + 1, hi⟩ ∈ {x | (ρ.symm x).val ≤ i.val + 1})
    (w : (G.induce {x | (ρ.symm x).val ≤ i.val + 1}).Walk ⟨ρ i, hu⟩ ⟨ρ ⟨i.val + 1, hi⟩, hv⟩),
    w.length ≤ k + 1

/-- **Packaging a within-prefix walk for the inner IH.** Given a set `P` propositionally equal to
the σ-prefix set `{x | (σ.symm x).val ≤ i+1}`, a walk in `G.induce P` joining the position-`i`
and position-`(i+1)` vertices of `σ` of length `≤ k+1` yields `WithinPrefixWalkLE G σ i hi k`.
(Used to feed the `p.tail` / single-edge walks of `lem:later` steps (2),(4) to the inner IH,
after transporting along the prefix-set equality `prefix_set_swap_eq`.) -/
theorem withinPrefixWalkLE_of_walk {G : SimpleGraph (Fin n)}
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n) (k : ℕ)
    (P : Set (Fin n)) (hP : P = {x | (σ.symm x).val ≤ i.val + 1})
    (hua : σ i ∈ P) (hva : σ ⟨i.val + 1, hi⟩ ∈ P)
    (q : (G.induce P).Walk ⟨σ i, hua⟩ ⟨σ ⟨i.val + 1, hi⟩, hva⟩)
    (hq : q.length ≤ k + 1) :
    WithinPrefixWalkLE G σ i hi k := by
  subst hP; exact ⟨hua, hva, q, hq⟩

/-- **Inner induction of `lem:later`** (gorProof tex:415-454). For a fixed position `i ≥ D` and
the outer IH `hIH : eqIH G e i.val`, induction on `k` (an upper bound on the number of interior
vertices of the shortest within-prefix path joining the swapped pair): if the vertices at
positions `i`, `i+1` of `ρ` are joined by a within-prefix walk of length `≤ k+1`, the
consecutive swap of `ρ` at position `i` transfers.

* `k = 0` base: a walk of length `1` is an edge, so the swapped pair is adjacent
  and `transfers_consecutive_edge` applies.
* `k+1` step: the 5 exchanges. Steps (1),(3),(5) are *early* swaps (positions
  `≤ i`) closed by `hIH` via `eqIH.transfers_early_swap`; steps (2),(4) are consecutive swaps
  along strictly shorter within-prefix walks closed by the inner IH at `k`. Chain via
  `Transfers.trans`. -/
theorem transfers_later_inner {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (i : Fin n) (hi : i.val + 1 < n) (_hiD : e ≤ i.val)
    (hIH : eqIH G e i.val) :
    ∀ (k : ℕ) (ρ : Equiv.Perm (Fin n)),
      WithinPrefixWalkLE G ρ i hi k → Transfers G e ρ (ρ * adjSwap i hi) := by
  intro k
  induction k with
  | zero =>
    -- BASE `k = 0`: the within-prefix walk has length `≤ 1`. If it has length `0` the two
    -- endpoints coincide — impossible (positions `i ≠ i+1` and `ρ` injective); hence length `1`,
    -- so `ρ i` and `ρ ⟨i+1⟩` are adjacent in the induced subgraph, hence in `G`. Edge case.
    intro ρ hw
    obtain ⟨hu, hv, w, hlen⟩ := hw
    -- length ≤ 1 and endpoints distinct ⟹ length = 1 ⟹ adjacency.
    have hne : ρ i ≠ ρ ⟨i.val + 1, hi⟩ := by
      intro h
      have := ρ.injective h
      simp only [Fin.ext_iff] at this
      omega
    -- The induced-subgraph walk of length ≤ 1 between distinct endpoints is a single edge.
    have hadj : (G.induce {x | (ρ.symm x).val ≤ i.val + 1}).Adj ⟨ρ i, hu⟩
        ⟨ρ ⟨i.val + 1, hi⟩, hv⟩ := by
      -- A walk of positive length whose length is `≤ 1` has length exactly `1`.
      have hpos : 0 < w.length := by
        rcases Nat.eq_zero_or_pos w.length with h0 | h0
        · exfalso; apply hne
          have := SimpleGraph.Walk.eq_of_length_eq_zero h0
          exact congrArg Subtype.val this
        · exact h0
      have hlen1 : w.length = 1 := by omega
      -- `Walk.adj_of_length_eq_one`: a length-1 walk is an edge.
      exact w.adj_of_length_eq_one hlen1
    -- Adjacency in the induced subgraph descends to `G`, then `transfers_consecutive_edge`.
    have hadjG : G.Adj (ρ i) (ρ ⟨i.val + 1, hi⟩) := hadj
    rw [mul_adjSwap_eq_trans]
    exact transfers_of_edge_swap G e ρ ⟨i.val + 1, hi⟩ rfl hadjG (hcard ρ)
  | succ k ihk =>
    -- STEP `k → k+1` (gorProof tex:425-454 / LSS tex:124-130). The 5 exchanges:
    --   σ¹ := ρ * swap i j₁                     -- (1) EARLY: positions i, j₁ ≤ i  → hIH
    --   σ² := σ¹ * adjSwap i hi                 -- (2) INNER: consec. swap at i, walk len ≤ k+1
    --   σ³ := σ² * swap i j₁                    -- (3) EARLY → hIH
    --   σ⁴ := σ³ * adjSwap i hi                 -- (4) INNER (single edge X–Z, len 1 ≤ k+1)
    --   ρ * adjSwap i hi = σ⁴ * swap i j₁       -- (5) EARLY → hIH  (by `five_swap_braid`)
    -- where `j₁ := ρ.symm Z` is the position of the FIRST INTERIOR vertex
    -- `Z := (bypass-path).getVert 1` of the shortest within-prefix walk joining `ρ i`, `ρ ⟨i+1⟩`.
    classical
    intro ρ hw
    set Pρ : Set (Fin n) := {x | (ρ.symm x).val ≤ i.val + 1} with hPρ
    obtain ⟨hu, hv, w, hlen⟩ := hw
    -- Endpoints distinct (positions `i ≠ i+1`, `ρ` injective).
    have hne : ρ i ≠ ρ ⟨i.val + 1, hi⟩ := by
      intro h; have := ρ.injective h; simp only [Fin.ext_iff] at this; omega
    -- Replace the walk by a PATH (`bypass`), of length `≤ k+2`, same endpoints. The shortest-path
    -- hypothesis of the source (gorProof tex:418-419) is realized as "a path", which guarantees
    -- the first interior vertex `getVert 1` is distinct from the far endpoint.
    set p := w.bypass with hp
    have hppath : p.IsPath := w.bypass_isPath
    have hplen : p.length ≤ w.length := w.length_bypass_le
    have hppos : 0 < p.length := by
      rcases Nat.eq_zero_or_pos p.length with h0 | h0
      · exact absurd (congrArg Subtype.val (SimpleGraph.Walk.eq_of_length_eq_zero h0)) hne
      · exact h0
    rcases Nat.lt_or_ge p.length 2 with hlt2 | hge2
    · -- `p.length = 1`: the endpoints are adjacent — the edge case (gorProof tex:424).
      have hp1 : p.length = 1 := by omega
      have hadjG : G.Adj (ρ i) (ρ ⟨i.val + 1, hi⟩) := p.adj_of_length_eq_one hp1
      rw [mul_adjSwap_eq_trans]
      exact transfers_of_edge_swap G e ρ ⟨i.val + 1, hi⟩ rfl hadjG (hcard ρ)
    · -- `p.length ≥ 2`: a genuine interior vertex exists.
      set zV : Fin n := (p.getVert 1 : Fin n) with hzV
      set j1 : Fin n := ρ.symm zV with hj1
      have hzVρ : ρ j1 = zV := by rw [hj1]; exact ρ.apply_symm_apply zV
      -- `ρ i` is adjacent to `Z` (first edge of the path), hence `Z ≠ ρ i`.
      have hadjRiZ : G.Adj (ρ i) zV := by
        have hadj01 : (G.induce Pρ).Adj (p.getVert 0) (p.getVert 1) :=
          p.adj_getVert_succ (by omega)
        rw [p.getVert_zero] at hadj01
        exact hadj01
      have hZneRi : zV ≠ ρ i := fun h => (G.loopless (ρ i)) (h ▸ hadjRiZ)
      -- `Z ≠ ρ ⟨i+1⟩` because `p` is a path: `getVert 1 ≠ getVert length` (1 ≠ length, both ≤ len).
      have hZneRv : zV ≠ ρ ⟨i.val + 1, hi⟩ := by
        intro h
        have hsub1 : (1 : ℕ) ∈ {j | j ≤ p.length} := by simp; omega
        have hsubL : p.length ∈ {j | j ≤ p.length} := by simp
        have heqsub : p.getVert 1 = p.getVert p.length := by
          rw [p.getVert_length]; exact Subtype.ext h
        have := hppath.getVert_injOn hsub1 hsubL heqsub
        omega
      -- `j₁` is a genuine interior position: `j₁.val ≤ i`, `j₁ ≠ i`, `j₁ ≠ i+1`.
      have hmemρsymm : (ρ.symm zV).val ≤ i.val + 1 := by
        have : zV ∈ Pρ := by rw [hzV]; exact (p.getVert 1).2
        simpa [hPρ, Set.mem_setOf_eq] using this
      have hZmem : zV ∈ Pρ := by rw [hzV]; exact (p.getVert 1).2
      have hj1nei1 : j1 ≠ (⟨i.val + 1, hi⟩ : Fin n) := by
        rw [hj1]; intro hcon; apply hZneRv; rw [← hzVρ, hj1, hcon]
      have hj1le : j1.val ≤ i.val := by
        have hjv : j1.val = (ρ.symm zV).val := by rw [hj1]
        by_contra hge
        have : j1.val = i.val + 1 := by omega
        exact hj1nei1 (Fin.ext this)
      have hj1nei : j1 ≠ i := by
        rw [hj1]; intro hcon; apply hZneRi; rw [← hzVρ, hj1, hcon]
      have hinei1 : i ≠ (⟨i.val + 1, hi⟩ : Fin n) := Fin.ne_of_val_ne (by simp)
      have hile : i.val ≤ i.val := le_refl _
      have hAS : adjSwap i hi = Equiv.swap i ⟨i.val + 1, hi⟩ := rfl
      -- INNER step (2): `σ¹ = ρ * swap i j₁`, with the within-prefix walk `Z → Y = p.tail`
      -- (length `= p.length - 1 ≤ k+1`).
      have step2 : Transfers G e (ρ * Equiv.swap i j1)
          ((ρ * Equiv.swap i j1) * adjSwap i hi) := by
        set σ1 := ρ * Equiv.swap i j1 with hσ1
        have hσ1i : σ1 i = ρ j1 := by
          rw [hσ1, Equiv.Perm.mul_apply, Equiv.swap_apply_left]
        have hσ1v : σ1 ⟨i.val + 1, hi⟩ = ρ ⟨i.val + 1, hi⟩ := by
          rw [hσ1, Equiv.Perm.mul_apply,
            Equiv.swap_apply_of_ne_of_ne (Ne.symm hinei1) (Ne.symm hj1nei1)]
        have hua1 : σ1 i ∈ Pρ := by rw [hσ1i, hzVρ]; exact hZmem
        have hva1 : σ1 ⟨i.val + 1, hi⟩ ∈ Pρ := by rw [hσ1v]; exact hv
        have hpnil : ¬ p.Nil := by rw [SimpleGraph.Walk.nil_iff_length_eq]; omega
        have htail_len : p.tail.length ≤ k + 1 := by
          have := SimpleGraph.Walk.length_tail_add_one hpnil; omega
        have hpsnd : (p.snd : Fin n) = (p.getVert 1 : Fin n) := by rw [SimpleGraph.Walk.snd]
        have hstart : (p.snd : Fin n) = (σ1 i : Fin n) := by rw [hpsnd, hσ1i, hzVρ]
        have hendpt : ((⟨ρ ⟨i.val + 1, hi⟩, hv⟩ : ↥Pρ) : Fin n) = (σ1 ⟨i.val + 1, hi⟩ : Fin n) := by
          rw [hσ1v]
        set q : (G.induce Pρ).Walk ⟨σ1 i, hua1⟩ ⟨σ1 ⟨i.val + 1, hi⟩, hva1⟩ :=
          p.tail.copy (Subtype.ext hstart) (Subtype.ext hendpt) with hq
        have hqlen : q.length ≤ k + 1 := by
          rw [hq, SimpleGraph.Walk.length_copy]; exact htail_len
        have hwithin : WithinPrefixWalkLE G σ1 i hi k := by
          refine withinPrefixWalkLE_of_walk σ1 i hi k Pρ ?_ hua1 hva1 q hqlen
          rw [hPρ, hσ1]
          exact (prefix_set_swap_eq ρ i i j1 (by omega) (by omega)).symm
        exact ihk σ1 hwithin
      -- INNER step (4): `σ³ = σ² * swap i j₁`, with the SINGLE-EDGE within-prefix walk `X → Z`
      -- (`ρ i` adjacent to `Z`, length `1 ≤ k+1`).
      have step4 : Transfers G e (ρ * Equiv.swap i j1 * adjSwap i hi * Equiv.swap i j1)
          ((ρ * Equiv.swap i j1 * adjSwap i hi * Equiv.swap i j1) * adjSwap i hi) := by
        set σ3 := ρ * Equiv.swap i j1 * adjSwap i hi * Equiv.swap i j1 with hσ3
        have e1 : (Equiv.swap i j1) i = j1 := Equiv.swap_apply_left i j1
        have e2 : (Equiv.swap i j1) j1 = i := Equiv.swap_apply_right i j1
        have e3 : (Equiv.swap i j1) (⟨i.val + 1, hi⟩ : Fin n) = ⟨i.val + 1, hi⟩ :=
          Equiv.swap_apply_of_ne_of_ne (Ne.symm hinei1) (Ne.symm hj1nei1)
        have f2 : (adjSwap i hi) (⟨i.val + 1, hi⟩ : Fin n) = i := Equiv.swap_apply_right _ _
        have f3 : (adjSwap i hi) j1 = j1 :=
          Equiv.swap_apply_of_ne_of_ne hj1nei hj1nei1
        have hσ3i : σ3 i = ρ i := by
          rw [hσ3]; simp only [Equiv.Perm.mul_apply, e1, f3, e2]
        have hσ3v : σ3 ⟨i.val + 1, hi⟩ = ρ j1 := by
          rw [hσ3]; simp only [Equiv.Perm.mul_apply, e3, f2, e1]
        have hua3 : σ3 i ∈ Pρ := by rw [hσ3i]; exact hu
        have hva3 : σ3 ⟨i.val + 1, hi⟩ ∈ Pρ := by rw [hσ3v, hzVρ]; exact hZmem
        have hadjind : (G.induce Pρ).Adj ⟨σ3 i, hua3⟩ ⟨σ3 ⟨i.val + 1, hi⟩, hva3⟩ := by
          change G.Adj (σ3 i) (σ3 ⟨i.val + 1, hi⟩)
          rw [hσ3i, hσ3v, hzVρ]; exact hadjRiZ
        set q : (G.induce Pρ).Walk ⟨σ3 i, hua3⟩ ⟨σ3 ⟨i.val + 1, hi⟩, hva3⟩ :=
          hadjind.toWalk with hq
        have hqlen : q.length ≤ k + 1 := by rw [hq]; simp [SimpleGraph.Walk.length_cons]
        have hwithin : WithinPrefixWalkLE G σ3 i hi k := by
          refine withinPrefixWalkLE_of_walk σ3 i hi k Pρ ?_ hua3 hva3 q hqlen
          rw [hPρ, hσ3, hAS]
          rw [prefix_set_swap_eq (ρ * Equiv.swap i j1 * Equiv.swap i ⟨i.val + 1, hi⟩)
              i i j1 (by omega) (by omega)]
          rw [prefix_set_swap_eq (ρ * Equiv.swap i j1) i i ⟨i.val + 1, hi⟩ (by omega) (by simp)]
          rw [prefix_set_swap_eq ρ i i j1 (by omega) (by omega)]
        exact ihk σ3 hwithin
      -- EARLY steps (1),(3),(5) via the outer IH `hIH` (`eqIH.transfers_early_swap`).
      have step1 : Transfers G e ρ (ρ * Equiv.swap i j1) :=
        hIH.transfers_early_swap ρ hile hj1le
      set σ2 := ρ * Equiv.swap i j1 * adjSwap i hi with hσ2
      have step3 : Transfers G e σ2 (σ2 * Equiv.swap i j1) :=
        hIH.transfers_early_swap σ2 hile hj1le
      set σ4 := ρ * Equiv.swap i j1 * adjSwap i hi * Equiv.swap i j1 * adjSwap i hi with hσ4
      have step5 : Transfers G e σ4 (σ4 * Equiv.swap i j1) :=
        hIH.transfers_early_swap σ4 hile hj1le
      -- Chain `ρ —1→ σ¹ —2→ σ² —3→ σ³ —4→ σ⁴ —5→ τ`.
      have hchain : Transfers G e ρ (σ4 * Equiv.swap i j1) :=
        (((step1.trans step2).trans step3).trans step4).trans step5
      -- The net composite equals `adjSwap i hi` by `five_swap_braid`.
      have hend : σ4 * Equiv.swap i j1 = ρ * adjSwap i hi := by
        rw [hσ4, hAS]
        have hbraid := five_swap_braid (i := i) (j1 := j1) (k := (⟨i.val + 1, hi⟩ : Fin n))
          hj1nei.symm hinei1 hj1nei1
        calc ρ * Equiv.swap i j1 * Equiv.swap i ⟨i.val + 1, hi⟩ * Equiv.swap i j1
              * Equiv.swap i ⟨i.val + 1, hi⟩ * Equiv.swap i j1
            = ρ * (Equiv.swap i j1 * Equiv.swap i ⟨i.val + 1, hi⟩ * Equiv.swap i j1
                * Equiv.swap i ⟨i.val + 1, hi⟩ * Equiv.swap i j1) := by simp [mul_assoc]
          _ = ρ * Equiv.swap i ⟨i.val + 1, hi⟩ := by rw [hbraid]
      rwa [hend] at hchain

/-- **`lem:later`** (gorProof tex:395-456), the 5-swap conjugation (non-edge, position `≥ D`).
Given the outer IH `hIH : eqIH G e i.val`, the non-edge consecutive swap at position `i ≥ D`
transfers. Proof: `Connectivity.lem_con` produces a within-prefix walk joining `σ i` and
`σ ⟨i+1⟩`; feed it (with `k := w.length` as the interior-vertex bound) to the inner induction
`transfers_later_inner`.

**0-based hypothesis.** The source `lem:later`/`lem:con`
require 1-based `i ≥ D` (= `e + 1`); the FIRST such case is 1-based `i = D`, which is 0-based
`i.val = e`.  Hence the Lean hypothesis is `hiD : e ≤ i.val` (was `e + 1 ≤ i.val`), and the
within-prefix walk is supplied by the weakened `lem_con` (`D ≤ i.val + 1`). -/
theorem transfers_later {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (hconn : IsKVertexConnected G (n - (e + 1)))
    (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n)
    (hiD : e ≤ i.val)
    (hIH : eqIH G e i.val)
    (_hnonedge : ¬ G.Adj (σ i) (σ ⟨i.val + 1, hi⟩)) :
    Transfers G e σ (σ * adjSwap i hi) := by
  -- gorProof `lem:later` tex:409-414: extract the within-prefix path from `lem_con`.
  -- 0-based: the FIRST `lem:later` case is `i.val = e` (1-based `i = D`), so `lem_con`'s
  -- weakened hypothesis is `D ≤ i.val + 1`, i.e. `e + 1 ≤ i.val + 1`, i.e. `e ≤ i.val`.
  have hreach : ReachableWithin G {x | (σ.symm x).val ≤ i.val + 1} (σ i) (σ ⟨i.val + 1, hi⟩) :=
    lem_con (D := e + 1) (by simpa [Nat.sub_sub] using hconn) σ i (by omega) hi
  obtain ⟨hu, hv, hr⟩ := hreach
  -- A concrete walk realizing the reachability (`Reachable.exists_isPath` then `.choose`).
  obtain ⟨w, _hwpath⟩ := hr.exists_isPath
  -- Feed it to the inner induction with bound `k := w.length` (so length `≤ k+1` trivially).
  refine transfers_later_inner hcard i hi hiD hIH w.length σ ?_
  exact ⟨hu, hv, w, by omega⟩

/-- **`lem:ats1` set equality for a within-`D` swap.** For a swap of positions
`i, i+1` strictly inside the first `D = e+1` positions (`i.val + 1 < e + 1`), the swapped
ordering `τ = σ * adjSwap i hi` has the same first-`D` vertex set as `σ`, in the order permuted
by the `Fin (e+1)`-transposition `w` of positions `i.val, i.val+1`:
`Ivtx τ hn = Ivtx σ hn ∘ w`. (`(σ * adjSwap i hi) x = σ (adjSwap i hi x)`, and on the first `D`
positions `adjSwap i hi = swap i ⟨i+1⟩` matches the `Fin (e+1)`-transposition.) gorProof
tex:313-319. -/
theorem ivtx_swap_within_D {e : ℕ}
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n) (hn : e + 1 ≤ n)
    (hiD1 : i.val + 1 < e + 1) :
    LSS.Ivtx (σ * adjSwap i hi) hn
      = LSS.Ivtx σ hn ∘ Equiv.swap (⟨i.val, by omega⟩ : Fin (e + 1)) ⟨i.val + 1, hiD1⟩ := by
  funext a
  simp only [Function.comp_apply, LSS.Ivtx, Equiv.Perm.mul_apply, adjSwap]
  -- Reduce to the `Fin n` argument equality inside `σ`.
  congr 1
  -- LHS: `swap i ⟨i+1,hi⟩ ⟨a.val, _⟩`; RHS: `⟨(swap ⟨i.val,_⟩ ⟨i.val+1,_⟩ a).val, _⟩`.
  -- Case on whether `a` is position `i`, `i+1`, or neither (matching the two swaps).
  rcases eq_or_ne (a.val) i.val with ha0 | ha0
  · -- `a` is position `i`: both swaps send it to position `i+1`.
    have haF : a = (⟨i.val, by omega⟩ : Fin (e + 1)) := Fin.ext ha0
    have hxF : (⟨a.val, lt_of_lt_of_le a.isLt hn⟩ : Fin n) = i := Fin.ext ha0
    rw [hxF, Equiv.swap_apply_left, haF, Equiv.swap_apply_left]
  · rcases eq_or_ne (a.val) (i.val + 1) with ha1 | ha1
    · -- `a` is position `i+1`: both swaps send it to position `i`.
      have haF : a = (⟨i.val + 1, hiD1⟩ : Fin (e + 1)) := Fin.ext ha1
      have hxF : (⟨a.val, lt_of_lt_of_le a.isLt hn⟩ : Fin n) = ⟨i.val + 1, hi⟩ := Fin.ext ha1
      rw [hxF, Equiv.swap_apply_right, haF, Equiv.swap_apply_right]
    · -- `a` is elsewhere: both swaps fix it.
      have hne0n : (⟨a.val, lt_of_lt_of_le a.isLt hn⟩ : Fin n) ≠ i :=
        fun h => ha0 (congrArg Fin.val h)
      have hne1n : (⟨a.val, lt_of_lt_of_le a.isLt hn⟩ : Fin n) ≠ ⟨i.val + 1, hi⟩ :=
        fun h => ha1 (congrArg Fin.val h)
      have hne0F : a ≠ (⟨i.val, by omega⟩ : Fin (e + 1)) :=
        fun h => ha0 (congrArg Fin.val h)
      have hne1F : a ≠ (⟨i.val + 1, hiD1⟩ : Fin (e + 1)) :=
        fun h => ha1 (congrArg Fin.val h)
      rw [Equiv.swap_apply_of_ne_of_ne hne0n hne1n,
          Equiv.swap_apply_of_ne_of_ne hne0F hne1F]

/-- **(PART B, sublemma #1 — tail invariance of the predecessor SET under a within-`D` swap.)**
For a within-`D` swap (`hb : i.val + 1 < e + 1`, so both swapped positions `i, i+1` are
strictly inside the first `D = e + 1`) and any TAIL vertex `v` (one whose `σ`-position is
`≥ e + 1`, i.e. `e + 1 ≤ (σ.symm v).val`), the preceding-non-neighbour SET is unchanged:
`precNonNbrσ G (σ * adjSwap i hi) v = precNonNbrσ G σ v`.

Both swapped vertices `σ_i, σ_{i+1}` sit at positions `< e + 1 ≤ (σ.symm v).val`, so they stay
strictly before every tail vertex; the swap fixes `v`'s own position (it is `> i + 1`); the
non-adjacency clause is identical. Only the precList ORDER (within the unchanged set) may flip,
which is exactly the `reorderPerm`/`yScale` sign content handled downstream. gorProof tex:323-361
(the `ψ`-tail, positions `≥ D`, is shared by `σ` and the within-`D`-swapped ordering). -/
theorem precNonNbrσ_adjSwap_withinD_tail {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n) (hb : i.val + 1 < e + 1)
    (v : Fin n) (hvtail : e + 1 ≤ (σ.symm v).val) :
    precNonNbrσ G (σ * adjSwap i hi) v = precNonNbrσ G σ v := by
  set τ : Equiv.Perm (Fin n) := σ * adjSwap i hi with hτdef
  -- `τ.symm u = (adjSwap i hi).symm (σ.symm u) = swap i ⟨i+1⟩ (σ.symm u)`.
  have hsymm : ∀ u, τ.symm u = (Equiv.swap i ⟨i.val + 1, hi⟩) (σ.symm u) := by
    intro u
    rw [hτdef]
    simp only [adjSwap]
    rfl
  -- `τ.symm v = σ.symm v` since `v`'s position `> i + 1` is fixed by the swap.
  have hsv : (τ.symm v).val = (σ.symm v).val := by
    rw [hsymm]
    rw [Equiv.swap_apply_of_ne_of_ne]
    · intro h; have := congrArg Fin.val h; simp at this; omega
    · intro h; have := congrArg Fin.val h; simp at this; omega
  -- The order clause is invariant: a value `< (σ.symm v).val` stays `< (σ.symm v).val`
  -- under `swap i ⟨i+1⟩` (the swap only permutes the values `i, i+1`, both `< e+1 ≤ pos v`).
  have horder : ∀ u, ((τ.symm u).val < (τ.symm v).val) ↔ ((σ.symm u).val < (σ.symm v).val) := by
    intro u
    rw [hsv, hsymm]
    -- `(swap i ⟨i+1⟩ (σ.symm u)).val < (σ.symm v).val ↔ (σ.symm u).val < (σ.symm v).val`.
    rcases eq_or_ne (σ.symm u) i with hui | hui
    · rw [hui, Equiv.swap_apply_left]
      simp only []; constructor <;> intro _ <;> omega
    · rcases eq_or_ne (σ.symm u) ⟨i.val + 1, hi⟩ with hui1 | hui1
      · rw [hui1, Equiv.swap_apply_right]
        simp only []; constructor <;> intro _ <;> omega
      · rw [Equiv.swap_apply_of_ne_of_ne hui hui1]
  ext u
  simp only [mem_precNonNbrσ, horder u]

/-! ### `lem:base1` / `lem:ats1`, the first-`D` density base (non-edge, `i < D`).

gorProof `lem:hasGOR` (tex:304-312), `lem:ats1` (tex:315-319), `lem:base1` (tex:323-361).

The source works with the `D`-vertex induced subgraph `G⁻`, where general
position is the single determinant attached to the only `D`-subset.

* **`lem:hasGOR` / `lem:dense` (gorProof tex:304-312),
  `DVertexBase.dense_ambDetLocus_Ivtx`:** for the `D = e+1` `ρ`-positions the
  determinant `ambDetI e (Ivtx ρ hn)` is nonzero
  (`NonEmpty.detI_phiσ_ne_zero_of_first`), hence its Euclidean non-vanishing
  locus is dense (`DVertexBase.dense_ambDetLocus_of_ne`, the `Fin m` to ambient
  transport of `AmbientDensity.dense_compl_zeroLocus_real`).
* **`lem:ats1` (gorProof tex:313-319),
  `DVertexBase.ambDetLocus_eq_of_ivtx_comp_perm`:** when `σ`, `τ` share the
  first-`D` vertex set in permuted order (`Ivtx τ = Ivtx σ ∘ w`), the two
  determinant loci coincide because the determinant differs only by `sign w`.
* **`lem:base1` ψ-pushforward (gorProof tex:323-361):** lift `D` vertices to
  `n` vertices through the shared tail `ψ = φ_{ρ_{D+1}} ∘ ⋯ ∘ φ_{ρ_n}`
  (positions `≥ D`, shared by `σ`,`τ`), using continuity
  `closure (ψ '' S) = closure (ψ '' closure S)`.

#### The kernel ↔ closure reduction (`LSS.ClosureReduction`)

`transfers_of_closure_eq` reduces `Transfers G e σ τ` to
`closure (range (ambRealPt σ)) = closure (range (ambRealPt τ))` (a polynomial vanishes on a set
iff on its closure, so equal closures ⟹ equal vanishing ideals ⟹ equal kernels). Thus the WHOLE
first-`D` base reduces to that single topological statement — `GOR⁺_σ(G) = GOR⁺_τ(G)` as Zariski
closures — which is the conclusion `lem:ats1`/`lem:base1` deliver via the common dense det-locus. -/

/-! **`lem:base1`/`lem:ats1` first-`D` closure-equality.**
For a non-edge swap of positions `i, i+1` with `i.val < e + 1` (within / at the boundary of the
first `D = e+1` positions), the two real ambient images have the same Euclidean closure:
`closure (range (ambRealPt σ)) = closure (range (ambRealPt τ))`, `τ = σ * adjSwap i hi`.

The decomposition from gorProof tex:301-361 uses the D-vertex determinant locus:

* **`lem:hasGOR` (gorProof tex:304-312):** the dense common subset is the single I-determinant
  non-vanishing locus `{g | ambDetReal e (Ivtx ρ hn) g ≠ 0}`, dense by
  `DVertexBase.dense_ambDetLocus_Ivtx` (`NonEmpty.detI_phiσ_ne_zero_of_first` ⟹
  nonzero polynomial ⟹ `DVertexBase.dense_ambDetLocus_of_ne`).
* **`lem:ats1` (gorProof tex:313-319):** for the `i.val < e` sub-case `σ`, `τ` share the
  first-`D` vertex set (the swap permutes positions within the first `D`), so
  `Ivtx τ hn = Ivtx σ hn ∘ w` and the two det-loci coincide
  (`DVertexBase.ambDetLocus_eq_of_ivtx_comp_perm`) — a common dense subset.
* **`lem:base1` ψ-pushforward (gorProof tex:323-361):** lift `D → n` through the shared tail
  `ψ` (positions `≥ D`); for the boundary `i.val = e` (swap straddles the `D`-boundary) this is
  where the `ψ`-tail genuinely moves a vertex across position `D`.

After the `lem:ats1` ordering-independence reduction
(`ivtx_swap_within_D` and `DVertexBase.ambDetLocus_eq_of_ivtx_comp_perm`), the
within-`D` case has a common determinant locus `L_σ`:

* `closure (range σ ∩ L_σ) = closure (range τ ∩ L_σ)`. The content is the `ψ`-tail realization:
  a point `g ∈ range (ambRealPt σ) ∩ L_σ` is the σ-construction output (an OR with first-`D` GP);
  since σ, τ agree on positions `≥ D`, its tail equals `φτ`'s tail up to a per-tail-vertex
  `y`-absorbable sign (the `yScale` mechanism of `transfers_of_edge_swap`), realizing
  `g = ambRealPt τ θ'`. Hence `range σ ∩ L_σ = range τ ∩ L_σ` as sets, and the closures agree.
-/

/-- The ambient parameterization point `ambRealPt G σ e θ` evaluated at the
coordinate `q = (v, c)` is the real construction `realPhi G σ e θ v c`:
`ambRealPt σ θ q = eval θ (ambSub σ q) = eval θ (phiσ σ q.1 q.2) = realPhi σ θ q.1 q.2`
(`eval_phiσ`). -/
theorem ambRealPt_apply {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (σ : Equiv.Perm (Fin n)) (θ : Fin n × ℕ → ℝ) (q : Fin n × Fin (e + 1)) :
    ambRealPt G σ e θ q = realPhi G σ e θ q.1 q.2 := by
  change MvPolynomial.eval θ (ambSub G σ e q) = realPhi G σ e θ q.1 q.2
  rw [ambSub]
  exact congrFun (eval_phiσ G σ e θ q.1) q.2

/-- `precList` length equals the predecessor-set card. -/
theorem precList_length_eq_card {G : SimpleGraph (Fin n)} [DecidableRel G.Adj]
    (ρ : Equiv.Perm (Fin n)) (v : Fin n) :
    (precList G ρ v).length = (precNonNbrσ G ρ v).card := by
  unfold precList; rw [Finset.length_sort]

/-- `precList` membership unfolds to the predecessor-set membership. -/
theorem precList_mem_iff {G : SimpleGraph (Fin n)} [DecidableRel G.Adj]
    (ρ : Equiv.Perm (Fin n)) (v u : Fin n) :
    u ∈ precList G ρ v ↔ u ∈ precNonNbrσ G ρ v := by
  unfold precList; rw [Finset.mem_sort]

/-- `precList` is `Nodup`. -/
theorem precList_nodup {G : SimpleGraph (Fin n)} [DecidableRel G.Adj]
    (ρ : Equiv.Perm (Fin n)) (v : Fin n) : (precList G ρ v).Nodup := by
  unfold precList; exact Finset.sort_nodup _ _

/-- Prefix version of `ImageChar.gp_indep_of_inj`: linear independence for any injective
subfamily of vertices whose `ρ`-positions lie in the first `D = e+1` slots, sourced only from
the first-`D` determinant/GP hypothesis. -/
theorem gp_first_indep_of_inj {e m : ℕ} (ρ : Equiv.Perm (Fin n)) (hn : e + 1 ≤ n)
    (f : Fin n → (Fin (e + 1) → ℝ))
    (hGP_first : LinearIndependent ℝ (fun a : Fin (e + 1) => f (Ivtx ρ hn a)))
    (g : Fin m → Fin n) (hg : Function.Injective g)
    (hgprefix : ∀ a : Fin m, (ρ.symm (g a)).val < e + 1) :
    LinearIndependent ℝ (fun a : Fin m => f (g a)) := by
  classical
  let α : Fin m → Fin (e + 1) := fun a => ⟨(ρ.symm (g a)).val, hgprefix a⟩
  have hαinj : Function.Injective α := by
    intro a b hab
    apply hg
    apply ρ.symm.injective
    apply Fin.ext
    simpa [α] using congrArg Fin.val hab
  have hcomp := hGP_first.comp α hαinj
  have hαeq : (fun a : Fin (e + 1) => f (Ivtx ρ hn a)) ∘ α = fun a : Fin m => f (g a) := by
    funext a
    simp [α, Ivtx]
  rwa [hαeq] at hcomp

/-- Prefix version of `ImageChar.gp_ne_zero`: every first-`D` vertex has nonzero vector,
sourced only from the first-`D` determinant/GP hypothesis. -/
theorem gp_first_ne_zero {e : ℕ} (ρ : Equiv.Perm (Fin n)) (hn : e + 1 ≤ n)
    (f : Fin n → (Fin (e + 1) → ℝ))
    (hGP_first : LinearIndependent ℝ (fun a : Fin (e + 1) => f (Ivtx ρ hn a)))
    (v : Fin n) (hvprefix : (ρ.symm v).val < e + 1) : f v ≠ 0 := by
  let a : Fin (e + 1) := ⟨(ρ.symm v).val, hvprefix⟩
  have h := hGP_first.ne_zero a
  simpa [a, Ivtx] using h

/-- A within-`D` adjacent swap preserves the first-`D` prefix as a vertex set. -/
theorem adjSwap_withinD_prefix_iff {e : ℕ}
    (ρ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n) (hb : i.val + 1 < e + 1)
    (v : Fin n) :
    (((ρ * adjSwap i hi).symm v).val < e + 1) ↔ ((ρ.symm v).val < e + 1) := by
  have hsymm : (ρ * adjSwap i hi).symm v = (Equiv.swap i ⟨i.val + 1, hi⟩) (ρ.symm v) := by
    simp only [adjSwap]
    rfl
  rw [hsymm]
  rcases eq_or_ne (ρ.symm v) i with hv0 | hv0
  · rw [hv0, Equiv.swap_apply_left]
    simp only []
    constructor <;> intro _ <;> omega
  · rcases eq_or_ne (ρ.symm v) ⟨i.val + 1, hi⟩ with hv1 | hv1
    · rw [hv1, Equiv.swap_apply_right]
      simp only []
      constructor <;> intro _ <;> omega
    · rw [Equiv.swap_apply_of_ne_of_ne hv0 hv1]

/-- Nonzero ambient determinant gives linear independence of the corresponding ambient rows. -/
theorem linearIndependent_rows_of_ambDetReal_ne_zero {e : ℕ}
    (Iv : Fin (e + 1) → Fin n) (g : Fin n × Fin (e + 1) → ℝ)
    (hdet : ambDetReal e Iv g ≠ 0) :
    LinearIndependent ℝ (fun a : Fin (e + 1) => fun c : Fin (e + 1) => g (Iv a, c)) := by
  classical
  set A : Matrix (Fin (e + 1)) (Fin (e + 1)) ℝ :=
    Matrix.of fun a c => g (Iv a, c)
  have hdetA : A.det ≠ 0 := by
    rw [ambDetReal, ambDetI] at hdet
    rw [RingHom.map_det] at hdet
    simpa [A, Matrix.map] using hdet
  exact Matrix.linearIndependent_rows_iff_isUnit.2
    ((Matrix.isUnit_iff_isUnit_det A).2 (isUnit_iff_ne_zero.2 hdetA))

/-- **(PART B, sublemma #2 — first-`D` GP-OR realization, truncating
    `ImageChar.exists_realPhi_eq`.)**
A real family `f : Fin n → Fin (e+1) → ℝ` that is OR/GP ONLY on the first-`D` prefix (positions
`< e + 1`) is realized by `realPhi` on that prefix: there is a `θ` with `realPhi G ρ e θ v = f v`
for every first-`D` vertex `v` (`(ρ.symm v).val < e + 1`).

The greedy sweep of `exists_realPhi_eq` only ever consults positions `< (ρ.symm v).val`, so
restricting the realization to the prefix needs only the prefix-restricted OR/GP hypotheses.
gorProof tex:304-312 (`lem:hasGOR`): for the `D`-vertex graph `G⁻` the GP condition is the
SINGLE determinant. -/
theorem exists_realPhi_eq_firstD (G : SimpleGraph (Fin n)) [DecidableRel G.Adj]
    (ρ : Equiv.Perm (Fin n)) (e : ℕ) (hn : e + 1 ≤ n)
    (hcard : ∀ v, (precNonNbrσ G ρ v).card ≤ e)
    (f : Fin n → (Fin (e + 1) → ℝ))
    (hOR_first : ∀ u v, (ρ.symm u).val < e + 1 → (ρ.symm v).val < e + 1 → u ≠ v →
      ¬ G.Adj u v → ∑ c, f u c * f v c = 0)
    (hGP_first : LinearIndependent ℝ (fun a : Fin (e + 1) => f (Ivtx ρ hn a))) :
    ∃ θ : Fin n × ℕ → ℝ, ∀ v : Fin n, (ρ.symm v).val < e + 1 → realPhi G ρ e θ v = f v := by
  classical
  suffices haux : ∀ p : ℕ, p ≤ e + 1 → ∃ θ : Fin n × ℕ → ℝ,
      ∀ u : Fin n, (ρ.symm u).val < p → realPhi G ρ e θ u = f u by
    obtain ⟨θ, hθ⟩ := haux (e + 1) le_rfl
    exact ⟨θ, fun v hv => hθ v hv⟩
  intro p hp
  induction p with
  | zero => exact ⟨fun _ => 0, fun u hu => by omega⟩
  | succ p ih =>
      have hp_prefix : p < e + 1 := by omega
      have hpn : p < n := lt_of_lt_of_le hp_prefix hn
      obtain ⟨θ, hθ⟩ := ih (by omega)
      set v : Fin n := ρ ⟨p, hpn⟩ with hv
      have hvpos : (ρ.symm v).val = p := by rw [hv]; simp
      set len : ℕ := (precList G ρ v).length with hlen
      have hlencard : len = (precNonNbrσ G ρ v).card := by
        rw [hlen]; exact precList_length_eq_card ρ v
      have hlen_le_e : len ≤ e := by rw [hlencard]; exact hcard v
      have hprec_pos : ∀ u ∈ precList G ρ v, (ρ.symm u).val < p := by
        intro u hu
        have huP : u ∈ precNonNbrσ G ρ v := (precList_mem_iff ρ v u).1 hu
        have := precNonNbrσ_lt G ρ huP
        rw [hvpos] at this
        exact this
      have hget_pos : ∀ j : Fin len, ((ρ.symm ((precList G ρ v).get j)).val) < p :=
        fun j => hprec_pos _ (List.get_mem _ _)
      set pl : Fin len → Fin n := fun j => (precList G ρ v).get j with hpl
      have hplinj : Function.Injective pl := by
        intro j₁ j₂ heq
        exact (List.nodup_iff_injective_get.1 (precList_nodup ρ v)) heq
      set w : Fin len → (Fin (e + 1) → ℝ) := fun j => f (pl j) with hw
      have hpl_prefix : ∀ j : Fin len, (ρ.symm (pl j)).val < e + 1 := by
        intro j
        rw [hpl]
        exact lt_trans (hget_pos j) hp_prefix
      have hwindep : LinearIndependent ℝ w := by
        rw [hw]
        exact gp_first_indep_of_inj ρ hn f hGP_first pl hplinj hpl_prefix
      have hfv0 : f v ≠ 0 := gp_first_ne_zero ρ hn f hGP_first v (by rw [hvpos]; exact hp_prefix)
      have hperp : ∀ j : Fin len, ∑ a, (f v) a * w j a = 0 := by
        intro j
        have hmem : pl j ∈ precList G ρ v := by rw [hpl]; exact List.get_mem _ _
        have huP : pl j ∈ precNonNbrσ G ρ v := (precList_mem_iff ρ v (pl j)).1 hmem
        have hnadj : ¬ G.Adj v (pl j) := ((mem_precNonNbrσ G ρ).1 huP).2
        have hne : v ≠ pl j := by
          intro h
          have := precNonNbrσ_lt G ρ huP
          rw [← h] at this
          exact (lt_irrefl _ this)
        have hvprefix : (ρ.symm v).val < e + 1 := by rw [hvpos]; exact hp_prefix
        have := hOR_first v (pl j) hvprefix (hpl_prefix j) hne hnadj
        rw [hw]
        exact this
      obtain ⟨x, c, hc, hcross⟩ :=
        crossMinors_surj_orthogonal hlen_le_e w hwindep (f v) hfv0 hperp
      set θ' : Fin n × ℕ → ℝ :=
        fun q =>
          if q.1 = v then
            (match q.2 with
             | 0 => 1 / c
             | Nat.succ s =>
                 if h : s / (e + 1) < e - len then
                   x ⟨s / (e + 1), h⟩ ⟨s % (e + 1), Nat.mod_lt _ (by omega)⟩
                 else 0)
          else θ q with hθ'
      have hreal_fix : ∀ u' : Fin n, (ρ.symm u').val < p →
          realPhi G ρ e θ' u' = realPhi G ρ e θ u' := by
        intro u' hu'
        apply realPhi_congr
        intro w' hw' s
        have hw'ne : w' ≠ v := by
          intro h; rw [h, hvpos] at hw'; omega
        rw [hθ']; simp only [hw'ne, if_false]
      have hmateq : (Matrix.of fun (a : Fin (e + 1)) (j : Fin e) =>
            match (precList G ρ v)[j.val]? with
            | some u =>
              if (ρ.symm u).val < (ρ.symm v).val then realPhi G ρ e θ' u a else 0
            | none => θ' (v, 1 + (((j.val - (precList G ρ v).length)) * (e + 1) + a.val)))
          = (Matrix.of fun (a : Fin (e + 1)) (cc : Fin e) =>
              if h : cc.val < len then w ⟨cc.val, h⟩ a
              else x ⟨cc.val - len, by omega⟩ a) := by
        funext a j
        simp only [Matrix.of_apply]
        by_cases hjlen : j.val < len
        · have hsome : (precList G ρ v)[j.val]? = some ((precList G ρ v).get ⟨j.val, hjlen⟩) := by
            rw [List.getElem?_eq_getElem hjlen]; rfl
          rw [hsome]
          have hposu : (ρ.symm ((precList G ρ v).get ⟨j.val, hjlen⟩)).val < (ρ.symm v).val := by
            rw [hvpos]; exact hget_pos ⟨j.val, hjlen⟩
          simp only [hposu, if_true, hjlen, dif_pos]
          rw [hreal_fix _ (by rw [hvpos] at hposu; exact hposu)]
          have hposu' : (ρ.symm ((precList G ρ v).get ⟨j.val, hjlen⟩)).val < p := by
            rw [hvpos] at hposu; exact hposu
          rw [hθ _ hposu']
        · have hnone : (precList G ρ v)[j.val]? = none := by
            rw [List.getElem?_eq_none_iff]; omega
          rw [hnone]
          simp only [hjlen, dif_neg, not_false_iff]
          rw [hθ']
          simp only [if_true]
          have hs : 1 + ((j.val - len) * (e + 1) + a.val)
              = Nat.succ ((j.val - len) * (e + 1) + a.val) := by omega
          rw [hs]
          have hdiv : ((j.val - len) * (e + 1) + a.val) / (e + 1) = j.val - len := by
            rw [add_comm, Nat.add_mul_div_right _ _ (by omega : 0 < e + 1),
              Nat.div_eq_of_lt a.isLt, zero_add]
          have hmod : ((j.val - len) * (e + 1) + a.val) % (e + 1) = a.val := by
            rw [add_comm, Nat.add_mul_mod_self_right, Nat.mod_eq_of_lt a.isLt]
          have hcond : ((j.val - len) * (e + 1) + a.val) / (e + 1) < e - len := by
            rw [hdiv]; omega
          change (if h : ((j.val - len) * (e + 1) + a.val) / (e + 1) < e - len then
                  x ⟨((j.val - len) * (e + 1) + a.val) / (e + 1), h⟩
                    ⟨((j.val - len) * (e + 1) + a.val) % (e + 1), Nat.mod_lt _ (by omega)⟩
                else 0) = x ⟨j.val - len, by omega⟩ a
          rw [dif_pos hcond]
          congr 1
          · exact Fin.ext hdiv
          · exact Fin.ext hmod
      have hθ'v0 : θ' (v, 0) = 1 / c := by rw [hθ']; simp
      have hrealv : realPhi G ρ e θ' v = f v := by
        funext bb
        rw [realPhi_eq]
        rw [hθ'v0]
        have hcross' :
            crossMinors (Matrix.of fun (a : Fin (e + 1)) (cc : Fin e) =>
              if h : cc.val < len then w ⟨cc.val, h⟩ a
              else x ⟨cc.val - len, by omega⟩ a) bb = (c • f v) bb := by
          rw [hcross]
        calc 1 / c * crossMinors (Matrix.of fun (a : Fin (e + 1)) (j : Fin e) =>
              match (precList G ρ v)[j.val]? with
              | some u =>
                if (ρ.symm u).val < (ρ.symm v).val then realPhi G ρ e θ' u a else 0
              | none => θ' (v, 1 + (((j.val - (precList G ρ v).length)) * (e + 1) + a.val))) bb
            = 1 / c * (c • f v) bb := by
              rw [congrArg (fun M => crossMinors M bb) hmateq, hcross']
          _ = f v bb := by
              simp only [Pi.smul_apply, smul_eq_mul]; field_simp
      refine ⟨θ', ?_⟩
      intro u' hu'
      rcases Nat.lt_succ_iff_lt_or_eq.1 hu' with hlt | heq
      · rw [hreal_fix u' hlt, hθ u' hlt]
      · have : u' = v := by
          rw [hv]
          apply ρ.symm.injective
          apply Fin.ext
          rw [heq]; simp
        rw [this]; exact hrealv

/-- **`crossMinors` is alternating in columns, over an arbitrary `CommRing R`** (the real-level
analogue of `OrderTransfer.crossMinors_col_perm`, which is stated only for `Poly n`). Permuting
the columns of `F` by `π` multiplies every coordinate of `crossMinors F` by `sign π`. -/
theorem crossMinors_col_perm_R {R : Type*} [CommRing R] {d : ℕ}
    (F : Matrix (Fin (d + 1)) (Fin d) R) (π : Equiv.Perm (Fin d)) (j : Fin (d + 1)) :
    crossMinors (F.submatrix id π) j = (Equiv.Perm.sign π : ℤ) • crossMinors F j := by
  simp only [crossMinors]
  have h1 : (F.submatrix id ⇑π).submatrix j.succAbove id
      = (F.submatrix j.succAbove id).submatrix id ⇑π := by
    ext a b; simp [Matrix.submatrix_apply]
  rw [h1, Matrix.det_permute', zsmul_eq_mul]
  ring

/-- **(PART B, sublemma #4 — tail-sign realization under a within-`D` swap.)** Let
`τ = σ * adjSwap i hi` be a within-`D` swap (`hb : i.val + 1 < e + 1`). Given a σ-parameter
`θσ` and a τ-parameter `θτ` whose
* first-`D` realizations already agree
  (`hfirst : ∀ v, (σ.symm v).val < e + 1 → realPhi G τ e θτ v = realPhi G σ e θσ v`), and whose
* tail `y`-scalars are the SIGN of the per-vertex precList reorder permutation and whose tail
  fresh-slots are copied from `θσ`
  (`htaily`, `htailfresh` below),

the tail realizations agree as well:
`∀ v, e + 1 ≤ (σ.symm v).val → realPhi G τ e θτ v = realPhi G σ e θσ v`.

Strong induction on the tail `σ`-position: by `precNonNbrσ_adjSwap_withinD_tail` the predecessor
SET of a tail vertex is unchanged, so the τ-`phiMat` columns are the σ-`phiMat` columns permuted
by `reorderPerm`; `crossMinors_col_perm` contributes the `± sign`, absorbed by the tail
`y`-scalar `θτ(v,0) = sign · θσ(v,0)`. gorProof tex:323-361. -/
theorem realPhi_tail_eq_of_adjSwap_withinD {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n) (hb : i.val + 1 < e + 1)
    (_hn : e + 1 ≤ n) (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (θσ θτ : Fin n × ℕ → ℝ)
    (hfirst : ∀ v, (σ.symm v).val < e + 1 →
      realPhi G (σ * adjSwap i hi) e θτ v = realPhi G σ e θσ v)
    -- Tail `y`-scalar = sign of the per-vertex precList reorder permutation `π v`, times `θσ`'s.
    (htaily : ∀ v (hvt : e + 1 ≤ (σ.symm v).val),
      θτ (v, 0) = (Equiv.Perm.sign
          (reorderPerm (precList G σ v) (precList G (σ * adjSwap i hi) v) e
            (by rw [precList_length_eq_card, precList_length_eq_card,
                  precNonNbrσ_adjSwap_withinD_tail σ i hi hb v hvt])
            (by rw [precList_length_eq_card]; exact hcard _ v)
            (by intro x; rw [precList_mem_iff, precList_mem_iff,
                  precNonNbrσ_adjSwap_withinD_tail σ i hi hb v hvt])
            (precList_nodup _ _)) : ℝ) * θσ (v, 0))
    -- Tail fresh-slots copied from `θσ`.
    (htailfresh : ∀ v, e + 1 ≤ (σ.symm v).val → ∀ s : ℕ, θτ (v, 1 + s) = θσ (v, 1 + s)) :
    ∀ v, e + 1 ≤ (σ.symm v).val →
      realPhi G (σ * adjSwap i hi) e θτ v = realPhi G σ e θσ v := by
  classical
  set τ : Equiv.Perm (Fin n) := σ * adjSwap i hi with hτdef
  -- precList length/membership/nodup bookkeeping, valid for TAIL vertices (predecessor set is
  -- unchanged: `precNonNbrσ_adjSwap_withinD_tail`).
  have hsetT : ∀ v, e + 1 ≤ (σ.symm v).val → precNonNbrσ G τ v = precNonNbrσ G σ v :=
    fun v hvt => precNonNbrσ_adjSwap_withinD_tail σ i hi hb v hvt
  have hlenT : ∀ v, e + 1 ≤ (σ.symm v).val →
      (precList G σ v).length = (precList G τ v).length := fun v hvt => by
    rw [precList_length_eq_card, precList_length_eq_card, hsetT v hvt]
  have hleT : ∀ v, e + 1 ≤ (σ.symm v).val → (precList G τ v).length ≤ e := fun v hvt => by
    rw [precList_length_eq_card]; exact hcard _ v
  have hmemT : ∀ v, e + 1 ≤ (σ.symm v).val → ∀ x, x ∈ precList G σ v ↔ x ∈ precList G τ v :=
    fun v hvt x => by rw [precList_mem_iff, precList_mem_iff, hsetT v hvt]
  -- the per-tail-vertex reorder permutation, matching `htaily`.
  set πv : ∀ v, e + 1 ≤ (σ.symm v).val → Equiv.Perm (Fin e) := fun v hvt =>
    reorderPerm (precList G σ v) (precList G τ v) e (hlenT v hvt) (hleT v hvt) (hmemT v hvt)
      (precList_nodup _ _) with hπvdef
  -- The strong-induction statement on the `σ`-position of a TAIL vertex.
  have key : ∀ N : ℕ, ∀ v : Fin n, (σ.symm v).val = N → e + 1 ≤ (σ.symm v).val →
      realPhi G τ e θτ v = realPhi G σ e θσ v := by
    intro N
    induction N using Nat.strong_induction_on with
    | _ N IH =>
      intro v hvN hvt
      -- The combined "agree below `v`" claim: for any predecessor `u` of `v` in `σ`, the two
      -- realizations agree (first-`D` via `hfirst`, earlier tail via the strong IH).
      have agree : ∀ u : Fin n, (σ.symm u).val < (σ.symm v).val →
          realPhi G τ e θτ u = realPhi G σ e θσ u := by
        intro u hu
        by_cases huD : (σ.symm u).val < e + 1
        · exact hfirst u huD
        · have hut : e + 1 ≤ (σ.symm u).val := by omega
          exact IH (σ.symm u).val (by omega) u rfl hut
      funext bb
      -- Unfold both `realPhi`s via the equation lemma `realPhi_eq` (well-founded recursive defs are
      -- NOT defeq to their unfolding, so `show` is not enough). We ASCRIBE the unfolded value to
      -- OUR
      -- hand-written `match` matrix (defeq to `realPhi_eq`'s internal matcher), so that after
      -- `rw [hτval, hσval]` the goal matrices use OUR matcher and `hcol`/`hcm` rewrite them.
      have hτval : realPhi G τ e θτ v bb
          = θτ (v, 0) * crossMinors (Matrix.of fun (a : Fin (e + 1)) (j : Fin e) =>
            match (precList G τ v)[j.val]? with
            | some u =>
              if (τ.symm u).val < (τ.symm v).val then realPhi G τ e θτ u a else 0
            | none => θτ (v, 1 + (((j.val - (precList G τ v).length)) * (e + 1) + a.val))) bb :=
        realPhi_eq G τ e θτ v bb
      have hσval : realPhi G σ e θσ v bb
          = θσ (v, 0) * crossMinors (Matrix.of fun (a : Fin (e + 1)) (j : Fin e) =>
            match (precList G σ v)[j.val]? with
            | some u =>
              if (σ.symm u).val < (σ.symm v).val then realPhi G σ e θσ u a else 0
            | none => θσ (v, 1 + (((j.val - (precList G σ v).length)) * (e + 1) + a.val))) bb :=
        realPhi_eq G σ e θσ v bb
      rw [hτval, hσval]
      -- Predecessor SET equality and the column identity `Mτ = Mσ.submatrix id (πv v hvt)`.
      have hcol : (Matrix.of fun (a : Fin (e + 1)) (c : Fin e) =>
            match (precList G τ v)[c.val]? with
            | some u =>
              if (τ.symm u).val < (τ.symm v).val then realPhi G τ e θτ u a else 0
            | none => θτ (v, 1 + (((c.val - (precList G τ v).length)) * (e + 1) + a.val)))
          = (Matrix.of fun (a : Fin (e + 1)) (c : Fin e) =>
              match (precList G σ v)[c.val]? with
              | some u =>
                if (σ.symm u).val < (σ.symm v).val then realPhi G σ e θσ u a else 0
              | none =>
                  θσ (v, 1 + (((c.val - (precList G σ v).length)) * (e + 1) + a.val))).submatrix
                id (πv v hvt) := by
        refine Matrix.ext fun a c => ?_
        simp only [Matrix.submatrix_apply, Matrix.of_apply, id_eq]
        by_cases hclt : c.val < (precList G τ v).length
        · -- precList block: read τ-vertex `u₂ = (precList G τ v)[c]`.
          have hu₂ : (precList G τ v)[c.val]? = some ((precList G τ v)[c.val]'hclt) :=
            List.getElem?_eq_getElem hclt
          set u₂ : Fin n := (precList G τ v)[c.val]'hclt with hu₂def
          have hu₂memτ : u₂ ∈ precNonNbrσ G τ v := by
            rw [← precList_mem_iff τ v u₂]; exact List.getElem_mem hclt
          have hu₂memσ : u₂ ∈ precNonNbrσ G σ v := by rw [← hsetT v hvt]; exact hu₂memτ
          have hguardτ : (τ.symm u₂).val < (τ.symm v).val := precNonNbrσ_lt G τ hu₂memτ
          have hguardσ : (σ.symm u₂).val < (σ.symm v).val := precNonNbrσ_lt G σ hu₂memσ
          -- σ-side column index `(πv v hvt c).val` lands in the precList block, same vertex `u₂`.
          have hπlt : ((πv v hvt) c).val < (precList G τ v).length := by
            simp only [hπvdef, reorderPerm_apply]
            exact reorderMap_lt _ _ _ _ _ _ hclt
          have hπltσ : ((πv v hvt) c).val < (precList G σ v).length := by
            rw [hlenT v hvt]; exact hπlt
          have hgetσ : (precList G σ v)[((πv v hvt) c).val]'hπltσ = u₂ := by
            simp only [hπvdef, reorderPerm_apply]
            exact reorderMap_getElem _ _ _ _ _ _ hclt
          have hu₂' : (precList G σ v)[((πv v hvt) c).val]? = some u₂ := by
            rw [List.getElem?_eq_getElem hπltσ, hgetσ]
          rw [hu₂, hu₂']
          dsimp only
          rw [if_pos hguardτ, if_pos hguardσ]
          exact congrFun (agree u₂ hguardσ) a
        · -- fresh block: both sides are the same `θ`-slot (copied via `htailfresh`).
          have hnoneτ : (precList G τ v)[c.val]? = none := List.getElem?_eq_none (by omega)
          have hπge : ((πv v hvt) c) = c := by
            simp only [hπvdef, reorderPerm_apply]
            exact reorderMap_ge _ _ _ _ _ _ hclt
          have hnoneσ : (precList G σ v)[((πv v hvt) c).val]? = none := by
            rw [hπge]; exact List.getElem?_eq_none (by rw [hlenT v hvt]; omega)
          rw [hnoneτ, hnoneσ, hπge]
          dsimp only
          rw [hlenT v hvt]
          exact htailfresh v hvt _
      -- assemble (term mode, to avoid `rw` on the `match`-built matrices): the column identity
      -- `hcol` + the column-permutation sign law `crossMinors_col_perm_R` give
      -- `crossMinors Mτ bb = sign(πv) • crossMinors Mσ bb`.
      have hcm : crossMinors (Matrix.of fun (a : Fin (e + 1)) (j : Fin e) =>
            match (precList G τ v)[j.val]? with
            | some u =>
              if (τ.symm u).val < (τ.symm v).val then realPhi G τ e θτ u a else 0
            | none => θτ (v, 1 + (((j.val - (precList G τ v).length)) * (e + 1) + a.val))) bb
          = (Equiv.Perm.sign (πv v hvt) : ℤ) •
            crossMinors (Matrix.of fun (a : Fin (e + 1)) (j : Fin e) =>
              match (precList G σ v)[j.val]? with
              | some u =>
                if (σ.symm u).val < (σ.symm v).val then realPhi G σ e θσ u a else 0
              | none => θσ (v, 1 + (((j.val - (precList G σ v).length)) * (e + 1) + a.val))) bb :=
        (congrArg (fun M => crossMinors M bb) hcol).trans
          (crossMinors_col_perm_R _ (πv v hvt) bb)
      -- The goal is now `θτ(v,0) * crossMinors Mτ bb = θσ(v,0) * crossMinors Mσ bb` with OUR
      -- matchers (from `hτval`/`hσval`); `rw [hcm]` rewrites the τ-crossMinors, `htaily` the
      -- τ-scalar; then `sign · sign = 1` cancels.
      rw [hcm, htaily v hvt, zsmul_eq_mul]
      have hsq : ((Equiv.Perm.sign (πv v hvt) : ℤ) : ℝ)
          * ((Equiv.Perm.sign (πv v hvt) : ℤ) : ℝ) = 1 := by
        rcases Int.units_eq_one_or (Equiv.Perm.sign (πv v hvt)) with h | h <;>
          simp [h]
      -- LHS = `(s * θσ(v,0)) * (s * cMσ)`; regroup to `(s*s) * (θσ(v,0) * cMσ) = θσ(v,0) * cMσ`.
      rw [mul_mul_mul_comm, hsq, one_mul]
  intro v hvt
  exact key (σ.symm v).val v rfl hvt

/-- For a within-`D` swap (`hb : i.val + 1 < e + 1`), the real ambient images
restricted to the common first-`D` det-locus `L_σ` coincide as sets:
`range (ambRealPt σ) ∩ L_σ = range (ambRealPt τ) ∩ L_σ`, `τ = σ * adjSwap i hi`,
`L_σ = {g | ambDetReal e (Ivtx σ hn) g ≠ 0}`.

In gorProof tex:301-361, a point
`g = ambRealPt σ θσ ∈ L_σ` is a σ-construction OR whose first-`D` block is GP (`g ∈ L_σ`);
its first-`D` part is realized by τ (`exists_realPhi_eq_firstD`) and its tail by τ up to the
`yScale` sign (`realPhi_tail_eq_of_adjSwap_withinD`), exhibiting `g ∈ range (ambRealPt τ)`.
Symmetric in `σ ↔ τ`. gorProof tex:301-361. -/
theorem range_inter_detLocus_eq_of_adjSwap_withinD {G : SimpleGraph (Fin n)}
    [DecidableRel G.Adj] {e : ℕ}
    (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n) (hb : i.val + 1 < e + 1)
    (hn : e + 1 ≤ n) (_hnonedge : ¬ G.Adj (σ i) (σ ⟨i.val + 1, hi⟩)) :
    (Set.range (fun θ => ambRealPt G σ e θ)) ∩ {g | ambDetReal e (Ivtx σ hn) g ≠ 0}
      = (Set.range (fun θ => ambRealPt G (σ * adjSwap i hi) e θ))
          ∩ {g | ambDetReal e (Ivtx σ hn) g ≠ 0} := by
  classical
  set sw : Equiv.Perm (Fin n) := adjSwap i hi
  set τ : Equiv.Perm (Fin n) := σ * sw
  have hsw : sw = adjSwap i hi := rfl
  have hτ : τ = σ * adjSwap i hi := by
    rw [show τ = σ * sw by rfl, hsw]
  have hτsw : τ * adjSwap i hi = σ := by
    rw [hτ]
    unfold adjSwap
    ext x
    simp
  have hIvστ : LSS.Ivtx τ hn
      = LSS.Ivtx σ hn ∘ Equiv.swap (⟨i.val, by omega⟩ : Fin (e + 1)) ⟨i.val + 1, hb⟩ := by
    rw [hτ]
    exact ivtx_swap_within_D σ i hi hn hb
  have hLτ_eq_Lσ :
      { g : Fin n × Fin (e + 1) → ℝ | ambDetReal e (Ivtx τ hn) g ≠ 0 }
        = { g : Fin n × Fin (e + 1) → ℝ | ambDetReal e (Ivtx σ hn) g ≠ 0 } :=
    LSS.ambDetLocus_eq_of_ivtx_comp_perm (G := G)
      (Equiv.swap (⟨i.val, by omega⟩ : Fin (e + 1)) ⟨i.val + 1, hb⟩) hIvστ
  have oneDir :
      ∀ (ρ : Equiv.Perm (Fin n)) (g : Fin n × Fin (e + 1) → ℝ),
        g ∈ Set.range (fun θ => ambRealPt G ρ e θ) →
        ambDetReal e (Ivtx (ρ * adjSwap i hi) hn) g ≠ 0 →
        g ∈ Set.range (fun θ => ambRealPt G (ρ * adjSwap i hi) e θ) := by
    intro ρ g hgRange hgdetTarget
    obtain ⟨θρ, rfl⟩ := hgRange
    set f : Fin n → Fin (e + 1) → ℝ := fun v => realPhi G ρ e θρ v with hf
    have hamb : ∀ v c, ambRealPt G ρ e θρ (v, c) = f v c := by
      intro v c
      rw [hf]
      exact ambRealPt_apply ρ θρ (v, c)
    have hOR_first : ∀ u v, ((ρ * adjSwap i hi).symm u).val < e + 1 →
        ((ρ * adjSwap i hi).symm v).val < e + 1 → u ≠ v →
        ¬ G.Adj u v → ∑ c, f u c * f v c = 0 := by
      intro u v _ _ huv hadj
      have hadjvu : ¬ G.Adj v u := by
        intro h
        exact hadj h.symm
      have hpoly := phiσ_isOR_poly (G := G) (σ := ρ) e huv hadjvu hadj (hcard ρ v) (hcard ρ u)
      have heval := congrArg (MvPolynomial.eval θρ) hpoly
      rw [map_sum] at heval
      simp only [map_mul, map_zero] at heval
      rw [hf]
      calc
        ∑ c, realPhi G ρ e θρ u c * realPhi G ρ e θρ v c
            = ∑ c, MvPolynomial.eval θρ (phiσ G ρ e u c) *
                MvPolynomial.eval θρ (phiσ G ρ e v c) := by
              apply Finset.sum_congr rfl
              intro c _
              rw [← congrFun (eval_phiσ G ρ e θρ u) c,
                  ← congrFun (eval_phiσ G ρ e θρ v) c]
        _ = 0 := heval
    have hGP_first : LinearIndependent ℝ
        (fun a : Fin (e + 1) => f (Ivtx (ρ * adjSwap i hi) hn a)) := by
      have hLI := linearIndependent_rows_of_ambDetReal_ne_zero
        (Ivtx (ρ * adjSwap i hi) hn) (ambRealPt G ρ e θρ) hgdetTarget
      have hsame :
          (fun a : Fin (e + 1) => fun c : Fin (e + 1) =>
              ambRealPt G ρ e θρ (Ivtx (ρ * adjSwap i hi) hn a, c))
            = fun a : Fin (e + 1) => f (Ivtx (ρ * adjSwap i hi) hn a) := by
        funext a c
        exact hamb _ _
      rwa [hsame] at hLI
    obtain ⟨θ0, hθ0⟩ :=
      exists_realPhi_eq_firstD G (ρ * adjSwap i hi) e hn (hcard _) f hOR_first hGP_first
    set θnew : Fin n × ℕ → ℝ := fun q =>
      if htail : e + 1 ≤ (ρ.symm q.1).val then
        match q.2 with
        | 0 =>
            (Equiv.Perm.sign
              (reorderPerm (precList G ρ q.1) (precList G (ρ * adjSwap i hi) q.1) e
                (by rw [precList_length_eq_card, precList_length_eq_card,
                      precNonNbrσ_adjSwap_withinD_tail ρ i hi hb q.1 htail])
                (by rw [precList_length_eq_card]; exact hcard _ q.1)
                (by intro x; rw [precList_mem_iff, precList_mem_iff,
                      precNonNbrσ_adjSwap_withinD_tail ρ i hi hb q.1 htail])
                (precList_nodup _ _)) : ℝ) * θρ (q.1, 0)
        | Nat.succ s => θρ (q.1, Nat.succ s)
      else θ0 q with hθnew
    have hfirst : ∀ v, (ρ.symm v).val < e + 1 →
        realPhi G (ρ * adjSwap i hi) e θnew v = realPhi G ρ e θρ v := by
      intro v hv
      have hvT : (((ρ * adjSwap i hi).symm v).val < e + 1) :=
        (adjSwap_withinD_prefix_iff ρ i hi hb v).2 hv
      have hcongr : realPhi G (ρ * adjSwap i hi) e θnew v
          = realPhi G (ρ * adjSwap i hi) e θ0 v := by
        apply realPhi_congr
        intro w hw s
        have hwT : (((ρ * adjSwap i hi).symm w).val < e + 1) := lt_of_le_of_lt hw hvT
        have hwρ : (ρ.symm w).val < e + 1 :=
          (adjSwap_withinD_prefix_iff ρ i hi hb w).1 hwT
        rw [hθnew]
        simp [not_le.mpr hwρ]
      rw [hcongr, hθ0 v hvT, hf]
    have htail := realPhi_tail_eq_of_adjSwap_withinD ρ i hi hb hn hcard θρ θnew hfirst
      (by
        intro v hvt
        rw [hθnew]
        simp only [dif_pos hvt])
      (by
        intro v hvt s
        rw [hθnew]
        simp only [dif_pos hvt]
        cases s <;> rfl)
    refine ⟨θnew, ?_⟩
    funext q
    rcases q with ⟨v, c⟩
    change ambRealPt G (ρ * adjSwap i hi) e θnew (v, c) = ambRealPt G ρ e θρ (v, c)
    rw [ambRealPt_apply (ρ * adjSwap i hi) θnew (v, c)]
    rw [hamb v c]
    rw [hf]
    by_cases hv : (ρ.symm v).val < e + 1
    · exact congrFun (hfirst v hv) c
    · have hvt : e + 1 ≤ (ρ.symm v).val := by omega
      exact congrFun (htail v hvt) c
  apply Set.Subset.antisymm
  · intro g hg
    rcases hg with ⟨hgRange, hgLσ⟩
    have hgLτ : ambDetReal e (Ivtx τ hn) g ≠ 0 := by
      have : g ∈ { g : Fin n × Fin (e + 1) → ℝ | ambDetReal e (Ivtx σ hn) g ≠ 0 } := hgLσ
      rw [← hLτ_eq_Lσ] at this
      exact this
    constructor
    · rw [hτ]
      exact oneDir σ g hgRange (by rwa [← hτ])
    · exact hgLσ
  · intro g hg
    rcases hg with ⟨hgRange, hgLσ⟩
    have hgRangeτ : g ∈ Set.range (fun θ => ambRealPt G τ e θ) := by
      rwa [hτ] at hgRange
    have hgBack : g ∈ Set.range (fun θ => ambRealPt G (τ * adjSwap i hi) e θ) :=
      oneDir τ g hgRangeτ (by rwa [hτsw])
    constructor
    · rwa [hτsw] at hgBack
    · exact hgLσ

/-- **`lem:base1`/`lem:ats1` first-`D` closure-equality, within-`D` only.**
For a non-edge swap STRICTLY inside the first `D = e+1` positions (`hiD : i.val + 1 < e + 1`)
the two real ambient images have the same Euclidean closure. This reduces via
`closure_range_eq_closure_range_inter_detLocus` and the ordering-independence
`ambDetLocus_eq_of_ivtx_comp_perm` to the set equality
`range_inter_detLocus_eq_of_adjSwap_withinD`. gorProof tex:301-361. -/
theorem firstD_base_closure_eq {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n)
    (hiD : i.val + 1 < e + 1) (hn : e + 1 ≤ n)
    (hnonedge : ¬ G.Adj (σ i) (σ ⟨i.val + 1, hi⟩)) :
    closure (Set.range (fun θ => ambRealPt G σ e θ))
      = closure (Set.range (fun θ => ambRealPt G (σ * adjSwap i hi) e θ)) := by
  -- gorProof tex:301-361, using the single I-determinant det-locus.
  -- `lem:hasGOR` image-glue: restrict both real
  -- images to the det-locus WITHOUT changing their closures
  -- (`closure_range_eq_closure_range_inter_detLocus`).
  rw [LSS.closure_range_eq_closure_range_inter_detLocus σ e hn,
      LSS.closure_range_eq_closure_range_inter_detLocus (σ * adjSwap i hi) e hn]
  -- Goal: compare the closures after restricting to determinant loci,
  --   `closure (range σ ∩ L_σ) = closure (range (σ * adjSwap i hi) ∩ L_{σ * adjSwap i hi})`,
  -- where `L_ρ = {g | ambDetReal e (Ivtx ρ hn) g ≠ 0}` is the single I-determinant det-locus.
  --
  -- This is `lem:base1`'s `ψ`-pushforward (gorProof tex:323-361): the construction factors as
  -- `φρ = ψ ∘ (first-`D` part)`, `ψ = φ_{ρ_{D+1}} ∘ ⋯ ∘ φ_{ρ_n}` SHARED by `σ` and the swapped
  -- ordering (the swap touches only positions `i, i+1 ≤ D`), so by continuity of `ψ`
  -- (`closure (ψ '' S) = closure (ψ '' closure S)`) the equal-closure of the first-`D` images
  -- lifts to the equal-closure of the full images. The first-`D` equal-closure is exactly
  -- `lem:ats1`, proved in `DVertexBase`:
  --   * within `D` (`i.val + 1 < e + 1`): the two det-loci coincide, `L_τ = L_σ`, since
  --     `Ivtx τ = Ivtx σ ∘ w` for the `Fin (e+1)`-transposition `w`
  --     (`ivtx_swap_within_D` + `DVertexBase.ambDetLocus_eq_of_ivtx_comp_perm`).
  -- This lemma handles the within-`D` case (`hiD : i.val + 1 < e + 1`), where the swap
  -- permutes positions inside the first `D`.
  set hb := hiD with hbdef
  -- `lem:ats1` ordering-independence: the two determinant loci coincide,
  -- `L_τ = L_σ`, since `Ivtx τ = Ivtx σ ∘ w` for the
  -- `Fin (e+1)`-transposition `w` of positions `i.val, i.val+1`
  -- (`ivtx_swap_within_D` + `DVertexBase.ambDetLocus_eq_of_ivtx_comp_perm`).
  have hIv : LSS.Ivtx (σ * adjSwap i hi) hn
      = LSS.Ivtx σ hn ∘ Equiv.swap (⟨i.val, by omega⟩ : Fin (e + 1)) ⟨i.val + 1, hb⟩ :=
    ivtx_swap_within_D σ i hi hn hb
  rw [LSS.ambDetLocus_eq_of_ivtx_comp_perm (G := G)
      (Equiv.swap (⟨i.val, by omega⟩ : Fin (e + 1)) ⟨i.val + 1, hb⟩) hIv]
  -- Goal is now `closure (range σ ∩ L_σ) = closure (range τ ∩ L_σ)` with the common det-locus
  -- `L_σ` on both sides: the two real images, restricted to the
  -- common first-`D`-GP det-locus, have the same Euclidean closure.
  --
  -- gorProof `lem:base1`, tex:323-361. Use the set equality
  -- `range_inter_detLocus_eq_of_adjSwap_withinD`:
  -- `range (ambRealPt σ) ∩ L_σ = range (ambRealPt τ) ∩ L_σ`.
  rw [range_inter_detLocus_eq_of_adjSwap_withinD hcard σ i hi hb hn hnonedge]

/-- **`lem:base1`/`lem:ats1`** (gorProof tex:301-361), the first-`D` density base, in
consecutive-swap output form. Reduced — via `transfers_of_closure_eq` — to the single
closure-equality `firstD_base_closure_eq`
(`closure (range (ambRealPt σ)) = closure (range (ambRealPt τ))`), whose density content is the
single I-determinant det-locus from `LSS.DVertexBase`.

`hn : e+1 ≤ n` is threaded from the caller (`transfers_consecutive`); it is needed for the
`D`-vertex determinant (`Ivtx`/`detI` standing assumption). -/
theorem transfers_firstD_base {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n)
    (hiD : i.val + 1 < e + 1) (hn : e + 1 ≤ n)
    (hnonedge : ¬ G.Adj (σ i) (σ ⟨i.val + 1, hi⟩)) :
    Transfers G e σ (σ * adjSwap i hi) :=
  -- Reduced to the closure-equality of the two real ambient images.
  transfers_of_closure_eq (σ := σ) (τ := σ * adjSwap i hi)
    (firstD_base_closure_eq hcard σ i hi hiD hn hnonedge)

/-- **The consecutive-swap building block** (`transfers_consecutive`). Combines the three cases:
edge (`transfers_consecutive_edge`), non-edge with position `≥ D` (`transfers_later`), and
non-edge with position `< D` (`transfers_firstD_base`). The `≥ D` case needs the outer IH
`eqIH G e i.val`, supplied by the caller. -/
theorem transfers_consecutive {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (hconn : IsKVertexConnected G (n - (e + 1)))
    (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (hn : e + 1 ≤ n)
    (σ : Equiv.Perm (Fin n)) (i : Fin n) (hi : i.val + 1 < n)
    (hIH : eqIH G e i.val) :
    Transfers G e σ (σ * adjSwap i hi) := by
  by_cases hedge : G.Adj (σ i) (σ ⟨i.val + 1, hi⟩)
  · exact transfers_consecutive_edge σ i hi hedge (hcard σ)
  · -- 0-based re-split (PART A): the FIRST `lem:later` case is `i.val = e`, so the
    -- `lem:later` machinery covers `e ≤ i.val`; the strictly-within-`D` case is `i.val + 1 < e +
    -- 1`.
    by_cases hlate : e ≤ i.val
    · exact transfers_later hconn hcard σ i hi hlate hIH hedge
    · exact transfers_firstD_base hcard σ i hi (by omega) hn hedge

/-! ## Part 3 — the outer `eqIH` induction and the headline `prop:order`.

The headline `prop:order` is the statement `eqIH G e (n-1)` (agreeing on positions `> n-1` is
vacuous, so `eqIH G e (n-1)` is *all* pairs of orderings). We prove `eqIH G e m` for every
`m ≥ e` by induction on `m` (gorProof tex:461-515, the outer induction):

* **base** `eqIH G e e` (gorProof `lem:base1` tex:323-361): orderings agreeing on positions
  `> e` (i.e. on positions `≥ D`) differ only by a rearrangement of their first `D` positions,
  reachable by consecutive swaps at positions `≤ e`, each closed by `transfers_firstD_base`.
* **step** `eqIH G e m → eqIH G e (m+1)` for `m ≥ e` (gorProof tex:464-512): orderings agreeing
  on positions `> m+1` are reduced — by rearranging their first `m+1` positions via the IH
  `eqIH G e m` — to a single `lem:later` consecutive swap at position `m+1`, then chained back. -/

/-! ### Shared permutation-support machinery for the outer induction.

Both the base (B) and the step (C) need the SAME structural fact: if two orderings `σ'`, `τ'`
agree on all positions `> i`, then the permutation `π = σ'⁻¹ * τ'` is *supported on the first
`i+1` positions* (`{0,…,i}`), and any such `π` is a product of **adjacent transpositions at
positions `j` with `j+1 ≤ i`** (each touching only positions `≤ i`). Feeding each adjacent swap
to the appropriate consecutive-swap brick and chaining `Transfers.trans` gives
`Transfers G e σ' (σ' * π) = Transfers G e σ' τ'`.

We package this as three proved helpers parameterized by the per-adjacent-swap brick
`hsw` (so B supplies firstD/edge bricks, C supplies firstD/edge/later bricks via the IH):

* `transfers_swap_le` — an ARBITRARY swap of two positions `x, y ≤ i` transfers, by reducing the
  gap `|x−y|` via the conjugation identity `swap a b = swap (a+1) a · swap b (a+1) · swap (a+1) a`
  (`Equiv.swap_mul_swap_mul_swap`), the outer two factors being adjacent swaps at position `a` and
  the middle factor having a strictly smaller gap (inner induction).
* `transfers_of_supported_le` — an ARBITRARY permutation `π` fixing all positions `> i` transfers
  `ρ` to `ρ * π`, by induction on `π.support.card` (`Equiv.Perm.card_support_swap_mul`), peeling
  one support swap `swap x (π x)` (both endpoints `≤ i`) at a time.
* `eqIH_of_adjSwap` — assembles `eqIH G e i` by applying `transfers_of_supported_le` to
  `π = σ'⁻¹ * τ'` (which fixes positions `> i` since `σ'`, `τ'` agree there) and rewriting
  `σ' * (σ'⁻¹ * τ') = τ'`. -/

/-- **Arbitrary swap of two early positions transfers.** Given the per-adjacent-swap brick
`hsw` (every adjacent swap at a position `j` with `j+1 ≤ i` transfers), the swap of ANY two
positions `x, y` with `x.val ≤ i` and `y.val ≤ i` transfers `ρ` to `ρ * Equiv.swap x y`.

Proof: WLOG `x.val < y.val` (the case `x = y` is `swap x x = 1`, reflexivity; `x.val > y.val`
is symmetric via `Equiv.swap_comm`). Induct on the gap `y.val - x.val`. Gap `1` is the adjacent
brick `hsw`. Otherwise write, with `a1 := x+1`,
`swap x y = swap a1 x · swap y a1 · swap a1 x` (`Equiv.swap_mul_swap_mul_swap`); the two outer
`swap a1 x = adjSwap x` are the adjacent brick, the middle `swap y a1` has gap `y − x − 1 < y − x`
and uses the inner induction. Chain via `Transfers.trans` and `mul_assoc`. -/
theorem transfers_swap_le {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ} {i : ℕ}
    (hsw : ∀ (ρ : Equiv.Perm (Fin n)) (j : Fin n) (hj : j.val + 1 < n), j.val + 1 ≤ i →
      Transfers G e ρ (ρ * adjSwap j hj))
    (ρ : Equiv.Perm (Fin n)) (x y : Fin n) (hx : x.val ≤ i) (hy : y.val ≤ i) :
    Transfers G e ρ (ρ * Equiv.swap x y) := by
  -- Strong induction on the gap `d = y.val - x.val` with `x.val < y.val` (then symmetrize).
  -- We prove the `x.val < y.val` case as an auxiliary, gap-indexed statement.
  suffices haux : ∀ (d : ℕ) (ρ : Equiv.Perm (Fin n)) (x y : Fin n), x.val ≤ i → y.val ≤ i →
      y.val = x.val + d → 0 < d → Transfers G e ρ (ρ * Equiv.swap x y) by
    rcases lt_trichotomy x.val y.val with hlt | heq | hgt
    · exact haux (y.val - x.val) ρ x y hx hy (by omega) (by omega)
    · have : x = y := Fin.ext heq
      subst this
      simpa [Equiv.swap_self] using Transfers.refl ρ
    · -- `y.val < x.val`: swap the roles, `swap x y = swap y x`.
      have h := haux (x.val - y.val) ρ y x hy hx (by omega) (by omega)
      rwa [Equiv.swap_comm] at h
  intro d
  induction d using Nat.strong_induction_on with
  | _ d ih =>
    intro ρ x y hx hy hyx hd
    -- The position one above `x` (well-defined since `x.val + 1 ≤ y.val ≤ i < n` is NOT needed:
    -- `x.val + 1 ≤ y.val < n` because `y < n`).
    have hx1n : x.val + 1 < n := by have := y.isLt; omega
    set a1 : Fin n := ⟨x.val + 1, hx1n⟩ with ha1
    -- `adjSwap x hx1n = swap x a1`.
    have hadj : adjSwap x hx1n = Equiv.swap x a1 := rfl
    -- Two cases: gap `1` (adjacent) or gap `≥ 2` (recurse on the middle swap).
    rcases Nat.lt_or_ge d 2 with hd2 | hd2
    · -- `d = 1`: `y = a1`, adjacent swap brick.
      have hd1 : d = 1 := by omega
      have hya1 : y = a1 := Fin.ext (by simp [ha1]; omega)
      subst hya1
      have := hsw ρ x hx1n (by simp [ha1] at hy ⊢; omega)
      rwa [hadj] at this
    · -- `d ≥ 2`: conjugation identity.
      -- `b ≠ a1` and `b ≠ x` (here `b = y`).
      have hya1 : y ≠ a1 := by
        intro h; apply hd2.not_gt; rw [Fin.ext_iff] at h; simp [ha1] at h; omega
      have hyx : y ≠ x := by
        intro h; rw [Fin.ext_iff] at h; omega
      -- `swap x y = swap a1 x * swap y a1 * swap a1 x`.
      have hdecomp : Equiv.swap x y = Equiv.swap a1 x * Equiv.swap y a1 * Equiv.swap a1 x :=
        (Equiv.swap_mul_swap_mul_swap hya1 hyx).symm
      -- `swap a1 x = swap x a1 = adjSwap x`.
      have hflip : Equiv.swap a1 x = adjSwap x hx1n := by rw [hadj, Equiv.swap_comm]
      -- Build the three-step chain. First step: `ρ → ρ * adjSwap x`.
      have ha1le : (a1 : Fin n).val ≤ i := by simp [ha1]; omega
      have step1 : Transfers G e ρ (ρ * adjSwap x hx1n) := hsw ρ x hx1n (by omega)
      set ρ1 : Equiv.Perm (Fin n) := ρ * Equiv.swap a1 x with hρ1
      have hρ1eq : ρ1 = ρ * adjSwap x hx1n := by rw [hρ1, hflip]
      -- Second step: `ρ1 → ρ1 * swap y a1` via the inner induction (smaller gap).
      have step2 : Transfers G e ρ1 (ρ1 * Equiv.swap y a1) := by
        -- `swap y a1 = swap a1 y` with gap `(y.val) - (a1.val) = d - 1 < d`.
        have hgap : y.val = (a1 : Fin n).val + (d - 1) := by simp [ha1]; omega
        have h := ih (d - 1) (by omega) ρ1 a1 y ha1le hy hgap (by omega)
        rwa [Equiv.swap_comm] at h
      set ρ2 : Equiv.Perm (Fin n) := ρ1 * Equiv.swap y a1 with hρ2
      -- Third step: `ρ2 → ρ2 * adjSwap x`.
      have step3 : Transfers G e ρ2 (ρ2 * adjSwap x hx1n) := hsw ρ2 x hx1n (by omega)
      -- Chain and identify the endpoint with `ρ * swap x y`.
      have step1' : Transfers G e ρ ρ1 := by rwa [hρ1eq]
      have hchain : Transfers G e ρ (ρ2 * adjSwap x hx1n) :=
        (step1'.trans step2).trans step3
      -- `ρ2 * adjSwap x = ρ * swap x y`. Convert `adjSwap x` to `swap a1 x` (via `← hflip`),
      -- then it is pure swap algebra against `hdecomp`.
      have hend : ρ2 * adjSwap x hx1n = ρ * Equiv.swap x y := by
        rw [hρ2, hρ1, ← hflip, hdecomp]
        simp only [mul_assoc]
      rwa [hend] at hchain

/-- **A permutation fixing all positions `> i` transfers `ρ` to `ρ * π`.** Given the per-adjacent
swap brick `hsw`, for any `π` with `π k = k` whenever `i < k.val`, `Transfers G e ρ (ρ * π)`.

Proof: induction on `π.support.card`. If `π = 1` (`support = ∅`), `ρ * 1 = ρ`, reflexivity.
Otherwise pick `x ∈ π.support`; both `x` and `y := π x` are in the support, hence have value
`≤ i` (a position `> i` is fixed, so not in the support). Write `π = swap x y · π''` with
`π'' = swap x y · π`; then `ρ * π = (ρ * swap x y) * π''`, and `transfers_swap_le` gives
`Transfers ρ (ρ * swap x y)` while the inner induction (`π''.support.card < π.support.card` by
`Equiv.Perm.card_support_swap_mul`, and `π''` still fixes positions `> i`) gives
`Transfers (ρ * swap x y) ((ρ * swap x y) * π'')`. Chain via `Transfers.trans` + `mul_assoc`. -/
theorem transfers_of_supported_le {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ} {i : ℕ}
    (hsw : ∀ (ρ : Equiv.Perm (Fin n)) (j : Fin n) (hj : j.val + 1 < n), j.val + 1 ≤ i →
      Transfers G e ρ (ρ * adjSwap j hj)) :
    ∀ (c : ℕ) (π : Equiv.Perm (Fin n)), π.support.card = c →
      (∀ k : Fin n, i < k.val → π k = k) →
      ∀ (ρ : Equiv.Perm (Fin n)), Transfers G e ρ (ρ * π) := by
  intro c
  induction c using Nat.strong_induction_on with
  | _ c ih =>
    intro π hc hfix ρ
    rcases Nat.eq_zero_or_pos c with hc0 | hcpos
    · -- `support.card = 0` ⟹ `π = 1`.
      subst hc0
      have hsupp : π.support = ∅ := Finset.card_eq_zero.mp hc
      have : π = 1 := Equiv.Perm.support_eq_empty_iff.mp hsupp
      subst this
      simpa using Transfers.refl ρ
    · -- pick `x ∈ support`.
      have hne : π.support.Nonempty := by
        rw [← Finset.card_pos, hc]; exact hcpos
      obtain ⟨x, hx⟩ := hne
      have hxne : π x ≠ x := Equiv.Perm.mem_support.mp hx
      -- both `x` and `π x` are in support ⟹ values `≤ i`.
      have hxle : x.val ≤ i := by
        by_contra h
        exact hxne (hfix x (by omega))
      have hpxsupp : π x ∈ π.support := Equiv.Perm.apply_mem_support.mpr hx
      have hpxle : (π x).val ≤ i := by
        by_contra h
        have : π (π x) ≠ π x := Equiv.Perm.mem_support.mp hpxsupp
        exact this (hfix (π x) (by omega))
      -- `π'' := swap x (π x) * π`. Support strictly smaller; still fixes `> i`.
      set π'' : Equiv.Perm (Fin n) := Equiv.swap x (π x) * π with hπ''
      have hcard'' : π''.support.card < c := by
        rw [hπ'', ← hc]; exact Equiv.Perm.card_support_swap_mul hxne
      have hfix'' : ∀ k : Fin n, i < k.val → π'' k = k := by
        intro k hk
        rw [hπ'', Equiv.Perm.mul_apply, hfix k hk]
        exact Equiv.swap_apply_of_ne_of_ne (by intro h; rw [h] at hk; omega)
          (by intro h; rw [h] at hk; omega)
      -- `π = swap x (π x) * π''` since `swap` is its own inverse.
      have hπsplit : π = Equiv.swap x (π x) * π'' := by
        rw [hπ'', ← mul_assoc, Equiv.swap_mul_self, one_mul]
      -- step1 : `ρ → ρ * swap x (π x)`.
      have step1 : Transfers G e ρ (ρ * Equiv.swap x (π x)) :=
        transfers_swap_le hsw ρ x (π x) hxle hpxle
      -- step2 : `(ρ * swap x (π x)) → (ρ * swap x (π x)) * π''` by inner IH.
      have step2 : Transfers G e (ρ * Equiv.swap x (π x))
          ((ρ * Equiv.swap x (π x)) * π'') :=
        ih π''.support.card hcard'' π'' rfl hfix'' (ρ * Equiv.swap x (π x))
      have hchain : Transfers G e ρ ((ρ * Equiv.swap x (π x)) * π'') := step1.trans step2
      -- identify `(ρ * swap x (π x)) * π'' = ρ * π`.
      have hend : (ρ * Equiv.swap x (π x)) * π'' = ρ * π := by
        rw [mul_assoc, ← hπsplit]
      rwa [hend] at hchain

/-- **`eqIH G e i` from the per-adjacent-swap brick.** If every adjacent swap at a position
`j` with `j+1 ≤ i` transfers (the brick `hsw`), then orderings agreeing on all positions `> i`
transfer — i.e. `eqIH G e i`.

Proof: for `σ'`, `τ'` agreeing on positions `> i`, set `π = σ'⁻¹ * τ'`. For `k` with `i < k.val`,
`σ' k = τ' k` gives `π k = σ'⁻¹ (τ' k) = σ'⁻¹ (σ' k) = k`, so `π` fixes all positions `> i`.
`transfers_of_supported_le` gives `Transfers G e σ' (σ' * π)`, and `σ' * (σ'⁻¹ * τ') = τ'`. -/
theorem eqIH_of_adjSwap {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ} {i : ℕ}
    (hsw : ∀ (ρ : Equiv.Perm (Fin n)) (j : Fin n) (hj : j.val + 1 < n), j.val + 1 ≤ i →
      Transfers G e ρ (ρ * adjSwap j hj)) :
    eqIH G e i := by
  intro σ' τ' hagree
  set π : Equiv.Perm (Fin n) := σ'⁻¹ * τ' with hπ
  have hfix : ∀ k : Fin n, i < k.val → π k = k := by
    intro k hk
    rw [hπ, Equiv.Perm.mul_apply, ← hagree k hk]
    exact Equiv.symm_apply_apply σ' k
  have h := transfers_of_supported_le hsw π.support.card π rfl hfix σ'
  rwa [show σ' * π = τ' by rw [hπ, ← mul_assoc, mul_inv_cancel, one_mul]] at h

/-- **Outer-induction base** `eqIH G e e` (gorProof `lem:base1` tex:323-361).

`eqIH G e e` says: orderings agreeing on all positions `> e` transfer. Two such orderings agree
on positions `≥ D = e+1` and differ only by a permutation of their first `D` positions
(`0,…,e`). That permutation factors into adjacent transpositions at positions `≤ e`
(`Equiv.Perm.mclosure_swap_castSucc_succ` restricted to the first-`D` block), each of which is a
consecutive swap closed by `transfers_firstD_base`; chain via `Transfers.trans`. This is the
first-`D` density base lifted to a full ordering rearrangement. -/
theorem eqIH_base {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (hn : e + 1 ≤ n) :
    eqIH G e e := by
  -- gorProof `lem:base1` tex:323-361: agree on positions `> e` ⟹ rearrangement of the first
  -- `D` positions ⟹ a product of position-`≤ e` consecutive swaps, each `transfers_firstD_base`
  -- (non-edge) or `transfers_consecutive_edge` (edge). Assembled by `eqIH_of_adjSwap`.
  refine eqIH_of_adjSwap (fun ρ j hj hjle => ?_)
  -- `j + 1 ≤ e ⟹ j.val + 1 < e + 1 = D`: the swapped pair is STRICTLY within the first `D`
  -- positions, so only the edge / first-`D` brick branches arise.
  have hjD : j.val + 1 < e + 1 := by omega
  by_cases hedge : G.Adj (ρ j) (ρ ⟨j.val + 1, hj⟩)
  · exact transfers_consecutive_edge ρ j hj hedge (hcard ρ)
  · exact transfers_firstD_base hcard ρ j hj hjD hn hedge

/-- **Outer-induction step** `eqIH G e m → eqIH G e (m+1)` for `m ≥ e` (gorProof tex:464-512).

Given the IH `hm : eqIH G e m`, prove `eqIH G e (m+1)`: let `σ', τ'` agree on positions
`> m+1`. If they also agree at position `m+1`, they agree on positions `> m`, so `hm` finishes.
Otherwise (gorProof tex:481-500) the two orderings, as sets, have equal first-`(m+2)` blocks;
the IH `hm` rearranges the first `m+1` positions of each into orderings `σ''`, `τ''` that differ
only by the single consecutive swap at position `m+1` of a non-edge pair (`transfers_later`,
position `m+1 ≥ D` since `m ≥ e`). Chain `σ' —hm→ σ'' —transfers_later→ τ'' —hm.symm→ τ'`. -/
theorem eqIH_step {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (hconn : IsKVertexConnected G (n - (e + 1)))
    (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (hn : e + 1 ≤ n)
    {m : ℕ} (_hme : e ≤ m) (hm : eqIH G e m) :
    eqIH G e (m + 1) := by
  -- gorProof tex:464-512. The source's "rearrange the first `i` numbers of the ordering, then
  -- one `lem:later` swap at position `i+1`" is, in the `Transfers` framing, exactly the
  -- supported-permutation decomposition `eqIH_of_adjSwap` (positions `> m+1` are fixed since
  -- `σ'`, `τ'` agree there): each adjacent swap at a position `j ≤ m` is closed by
  -- `transfers_consecutive`, whose `later` branch (position `j ≥ D = e+1`) consumes the IH
  -- `eqIH G e j.val`, available from `hm : eqIH G e m` since `j.val ≤ m` (`eqIH` is monotone:
  -- agreement on `> j` is stronger than agreement on `> m` when `j ≤ m`).
  refine eqIH_of_adjSwap (fun ρ j hj hjle => ?_)
  -- `j + 1 ≤ m + 1 ⟹ j.val ≤ m`. Derive `eqIH G e j.val` from `hm` by monotonicity.
  have hjm : j.val ≤ m := by omega
  have hIHj : eqIH G e j.val := by
    intro a b hab
    exact hm a b (fun k hk => hab k (by omega))
  exact transfers_consecutive hconn hcard hn ρ j hj hIHj

/-- **Outer induction**: `eqIH G e m` for every `m ≥ e` (gorProof tex:461-515), by induction on
`m` from the base `eqIH_base` via the step `eqIH_step`. -/
theorem eqIH_of_ge {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] {e : ℕ}
    (hconn : IsKVertexConnected G (n - (e + 1)))
    (hcard : ∀ (ρ : Equiv.Perm (Fin n)) v, (precNonNbrσ G ρ v).card ≤ e)
    (hn : e + 1 ≤ n) :
    ∀ m : ℕ, e ≤ m → eqIH G e m := by
  intro m
  induction m with
  | zero => intro h; have : e = 0 := Nat.le_zero.mp h; subst this; exact eqIH_base hcard hn
  | succ m ihm =>
    intro hle
    rcases Nat.lt_or_ge e (m + 1) with hlt | hge
    · -- `e ≤ m`, use the step on `ihm`.
      have hme : e ≤ m := by omega
      exact eqIH_step hconn hcard hn hme (ihm hme)
    · -- `e = m + 1`, this is the base index itself.
      have : e = m + 1 := by omega
      subst this; exact eqIH_base hcard hn

/-- **`prop:order`** (gorProof `prop:order` tex:289-293, LSS Main Lemma 1.3 tex:116).

If `G` is `(n − D)`-connected (`D = e + 1`) and every vertex has at most `e` preceding
non-neighbours in every ordering (the `hcard` hypothesis, supplied by connectivity via
`HIndep`), then for ALL orderings `σ, τ`, `Transfers G e σ τ` — i.e. `GOR⁺_σ` and `GOR⁺_τ`
are ATS.

Proof: `prop:order` is `eqIH G e (n-1)` (agreement on positions `> n-1` is vacuous, hence
*all* pairs). `eqIH_of_ge` supplies `eqIH G e (n-1)` since `n-1 ≥ e` (from `e+1 ≤ n`); apply it
with the vacuously-true agreement hypothesis. -/
theorem prop_order {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] (e : ℕ)
    (hconn : IsKVertexConnected G (n - (e + 1)))
    (hcard : ∀ (σ : Equiv.Perm (Fin n)) v, (precNonNbrσ G σ v).card ≤ e)
    (hn : e + 1 ≤ n)
    (σ τ : Equiv.Perm (Fin n)) :
    Transfers G e σ τ := by
  have hge : e ≤ n - 1 := by omega
  have hIH : eqIH G e (n - 1) := eqIH_of_ge hconn hcard hn (n - 1) hge
  refine hIH σ τ (fun k hk => ?_)
  -- `k.val < n`, so `n - 1 < k.val` is impossible: the agreement hypothesis is vacuous.
  have := k.isLt
  omega

/-- **Per-`I` corollary** (gorProof tex:517-537, `lem:nonempt1` + `prop:order`).

For ANY ordering `σ` and any `D`-subset realized as the first `D` vertices of some ordering `τ`
(here given as `τ` directly, with `I = {τ_0,…,τ_{D-1}}`), the construction determinant of those
`I`-vertices is nonzero under `σ`:
`det (φσ(Ivtx τ a) b) ≠ 0`.

Proof: `prop_order` gives `Transfers G e σ τ`; `detI_phiσ_ne_zero_of_first` gives the τ-side
nonvanishing `detI G τ e hn ≠ 0` (= `det (φτ(Ivtx a) b) ≠ 0`); `Transfers.detI_ne_zero`
transports it to the σ side. This is the input to the final `Δσ = ∏_I det_I(φσ) ≠ 0`
assembly (left to a separate file). -/
theorem detI_phiσ_ne_zero {G : SimpleGraph (Fin n)} [DecidableRel G.Adj] (e : ℕ)
    (hconn : IsKVertexConnected G (n - (e + 1)))
    (hcard : ∀ (σ : Equiv.Perm (Fin n)) v, (precNonNbrσ G σ v).card ≤ e)
    (σ τ : Equiv.Perm (Fin n)) (hn : e + 1 ≤ n) :
    Matrix.det (Matrix.of fun (a b : Fin (e + 1)) => phiσ G σ e (Ivtx τ hn a) b) ≠ 0 := by
  have htr : Transfers G e σ τ := prop_order e hconn hcard hn σ τ
  have hτ : Matrix.det (Matrix.of fun (a b : Fin (e + 1)) => phiσ G τ e (Ivtx τ hn a) b) ≠ 0 := by
    have := detI_phiσ_ne_zero_of_first G τ e hn
    rwa [detI] at this
  exact htr.detI_ne_zero (Ivtx τ hn) hτ

end LSS
